/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.carlos.app_cliente_proyecto1.UI;

import com.carlos.app_cliente_proyecto1.HttpMethods.SolicitudesApi;
import com.carlos.app_cliente_proyecto1.Lexer.lexerIndigo;
import com.carlos.app_cliente_proyecto1.Objetos.mensaje;
import com.carlos.app_cliente_proyecto1.Objetos.usuario;
import com.carlos.app_cliente_proyecto1.Parser.parserIndigo;

import java.awt.TextArea;
import java.io.StringReader;
import java.util.List;

import javax.swing.JTextArea;

/**
 *
 * @author benjamin
 */
public class EditorTexto extends javax.swing.JInternalFrame {
    
    private usuario currentUser = null;
    
    private SolicitudesApi api = new SolicitudesApi();
    
    /**
     * Creates new form EditorTexto
     */
    public EditorTexto(usuario currentUser) {
        initComponents();
        this.currentUser=currentUser;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        editorTexto = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        labelLinea = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelColumna = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        resIndigo = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        resNormal = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        btnCopiar = new javax.swing.JMenuItem();
        btnPegar = new javax.swing.JMenuItem();
        btnCortar = new javax.swing.JMenuItem();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        editorTexto.setColumns(20);
        editorTexto.setRows(5);
        editorTexto.setTabSize(3);
        editorTexto.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                editorTextoCaretUpdate(evt);
            }
        });
        jScrollPane1.setViewportView(editorTexto);

        jLabel1.setText("Respuesta Traducida");

        jLabel2.setText("Respuesta Indigo");

        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Linea:");

        labelLinea.setText("1");

        jLabel4.setText("Columna:");

        labelColumna.setText("1");

        resIndigo.setEditable(false);
        resIndigo.setColumns(20);
        resIndigo.setRows(5);
        resIndigo.setTabSize(3);
        resIndigo.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                resIndigoCaretUpdate(evt);
            }
        });
        jScrollPane4.setViewportView(resIndigo);

        resNormal.setEditable(false);
        resNormal.setColumns(20);
        resNormal.setRows(5);
        resNormal.setTabSize(3);
        resNormal.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                resNormalCaretUpdate(evt);
            }
        });
        jScrollPane5.setViewportView(resNormal);

        jMenu2.setText("Edicion");

        btnCopiar.setText("Copiar");
        btnCopiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCopiarActionPerformed(evt);
            }
        });
        jMenu2.add(btnCopiar);

        btnPegar.setText("Pegar");
        btnPegar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPegarActionPerformed(evt);
            }
        });
        jMenu2.add(btnPegar);

        btnCortar.setText("Cortar");
        btnCortar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCortarActionPerformed(evt);
            }
        });
        jMenu2.add(btnCortar);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelLinea)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelColumna)
                        .addGap(169, 169, 169)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(labelLinea)
                            .addComponent(labelColumna)
                            .addComponent(jButton1))
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editorTextoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_editorTextoCaretUpdate
        // TODO add your handling code here:
        JTextArea editArea = (JTextArea) evt.getSource();
        int linea = 1;
        int columna = 1;
        try {
            int caretpos = editArea.getCaretPosition();
            linea = editArea.getLineOfOffset(caretpos);
            columna = caretpos - editArea.getLineStartOffset(linea);

            // Ya que las líneas las cuenta desde la 0
            linea += 1;
            if (columna == 0) {
                columna = 1;
            }

            labelLinea.setText(String.valueOf(linea));
            labelColumna.setText(String.valueOf(columna));

        } catch (Exception ex) {
        }
    }//GEN-LAST:event_editorTextoCaretUpdate

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String envio = editorTexto.getText();
        String respuesta = api.envioRespuesta(envio);
        resIndigo.setText(respuesta);
        lecturaMensaje(respuesta);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void lecturaMensaje(String respuesta){
        try {
            lexerIndigo lex = new lexerIndigo(new StringReader(respuesta));
            parserIndigo parser = new parserIndigo(lex);
            parser.parse();

            List<mensaje> res1 = parser.getErrLex();
            List<mensaje> res2 = parser.getErrSin();
            List<mensaje> res3 = parser.getMsjUser();

            String contenido = "";
            
            for (int i = (res1.size()-1); i >=0 ; i--) {
                contenido = contenido + res1.get(i).getMensaje()+"\n";
            }
            
            for (int i = (res2.size()-1); i >=0 ; i--) {
                contenido = contenido + res2.get(i).getMensaje()+"\n";
            }
            
            for (int i = (res3.size()-1); i >=0 ; i--) {
                contenido = contenido + res3.get(i).getMensaje()+"\n";
            }
            resNormal.setText(contenido);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void resIndigoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_resIndigoCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_resIndigoCaretUpdate

    private void resNormalCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_resNormalCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_resNormalCaretUpdate

    private void btnCortarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCortarActionPerformed
        // TODO add your handling code here:
        this.editorTexto.cut();
    }//GEN-LAST:event_btnCortarActionPerformed

    private void btnCopiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopiarActionPerformed
        // TODO add your handling code here:
        this.editorTexto.copy();
    }//GEN-LAST:event_btnCopiarActionPerformed

    private void btnPegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPegarActionPerformed
        // TODO add your handling code here:
        this.editorTexto.paste();
    }//GEN-LAST:event_btnPegarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnCopiar;
    private javax.swing.JMenuItem btnCortar;
    private javax.swing.JMenuItem btnPegar;
    private javax.swing.JTextArea editorTexto;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel labelColumna;
    private javax.swing.JLabel labelLinea;
    private javax.swing.JTextArea resIndigo;
    private javax.swing.JTextArea resNormal;
    // End of variables declaration//GEN-END:variables
}
