
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.carlos.app_cliente_proyecto1.Parser;

/** CUP generated class containing symbol constants. */
public class parserIndigoSym {
  /* terminals */
  public static final int MAYOR_QUE = 3;
  public static final int MENOR_QUE = 2;
  public static final int error = 1;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MENOR_QUE",
  "MAYOR_QUE"
  };
}

