package com.carlos.app_cliente_proyecto1.Parser;

import com.carlos.app_cliente_proyecto1.Lexer.lexerIndigo;
import com.carlos.app_cliente_proyecto1.Objetos.*;
import com.carlos.app_cliente_proyecto1.Tokens.token;

import java.util.ArrayList;
import java_cup.runtime.Symbol;
import java.util.List;

class parserIndigo;

parser code {:
        private List<String> errorsList = new ArrayList();
        private usuario logUser = new usuario();

        //LISTAS DE OBJETOS RECUPERADOS DE LAS PRODUCCIONES
        //------LISTA ELIMINACION DE USUARIO
        List<usuario> delUser = new ArrayList<>();
        public List<usuario> getDelUser() {
                return delUser;
        }
        //------LISTA DE CREACION DE USUARIO
        List<usuario> createUser = new ArrayList<>();
        public List<usuario> getCreateUser() {
                return createUser;
        }
        //-----LSIAT DE MODIFICACION DE USUARIOS
        List<userNew> modUser = new ArrayList<>();
        public List<userNew> getModUser() {
                return modUser;
        }   
        //-----LISTA DE FORMULARIOS NUEVOS
        List<formulario> newForms = new ArrayList<>();
        public List<formulario> getNewForms() {
            return newForms;
        }
        //------LISTA DE FORMULARIOS A ELIMINAR
        List<formulario> delForm = new ArrayList<>();
        public List<formulario> getDelForm() {
            return delForm;
        }
        //------LSITA DE FORMULARIOS A MODIFICAR
        List<formulario> modForm = new ArrayList<>();
        public List<formulario> getModForm() {
            return modForm;
        }
        //-----LSITA DE COMPONENTES A ELIMINAR
        List<componente> delComp = new ArrayList<>();
        public List<componente> getDelComp() {
            return delComp;
        }
        //----LISTA DE COMPONENTES A AGREGAR
        List<componente> addComp = new ArrayList<>();
        public List<componente> getAddComp() {
            return addComp;
        }
        //---LISTA DE COMPONENTES A MODIFICAR
        List<componente> modComp = new ArrayList<>();
        public List<componente> getModComp() {
            return modComp;
        }

        //--LISTA DE ERRORES LEXICOS
        List<mensaje> errLex = new ArrayList<>();
        public List<mensaje> getErrLex() {
            return errLex;
        }
        //--LISTA DE ERRORES SINTACTICOS
        List<mensaje> errSin = new ArrayList<>();
        public List<mensaje> getErrSin() {
            return errSin;
        }
        //--LISTA DE MENSAJES A USUARIO
        List<mensaje> msjUser = new ArrayList<>();
        public List<mensaje> getMsjUser() {
            return msjUser;
        }
        //LISTA DE INSTRUCCIONES A REALIZAR
        List<Object> instrucciones = new ArrayList<>();
        public List<Object> getInstrucciones() {
            return instrucciones;
        }

        public usuario getLogUser() {
                return logUser;
        }
        public parserIndigo(lexerIndigo lex){
                super(lex);
        }

        public void report_error(String message, Object info){
                Symbol symbol = cur_token;
                token tok = (token)symbol.value;
                if (tok != null) {
                        System.out.println("Parametro inesperado: |" + ((tok.getLexeme().equals("\"")) ? "comilla" : tok.getLexeme()) + "| Linea: " + tok.getLine() + ", Columna: " + tok.getColumn());
                        errorsList.add("Parametro inesperado: |" + ((tok.getLexeme().equals("\"")) ? "comilla" : tok.getLexeme()) + "| Linea: " + tok.getLine() + ", Columna: " + tok.getColumn());
                }
        }

        public void report_fatal_error(String message, Object info){
                System.out.println(info.toString());
                System.out.println("reportfatal");
        }
        
        public void errorVerificacion(String mensage,Object info){
                token tok = (token)info;
                System.out.println(mensage+"Componente ubicado en Linea: "+tok.getLine()+", Columna: "+tok.getColumn());
                errorsList.add(mensage+"Componente ubicado en Linea: "+tok.getLine()+", Columna: "+tok.getColumn());
        }

        public void errorParametroDuplicado(Object simbolo){
                token tok = (token)((Symbol)simbolo).value;
                System.out.println("El parametro del componente ubicado en Linea: "+tok.getLine()+", Columna: "+tok.getColumn()+" ya se habia definido con anterioridad");
                errorsList.add("El parametro del componente ubicado en Linea: "+tok.getLine()+", Columna: "+tok.getColumn()+" ya se habia definido con anterioridad");
        }
        /*
        public void syntax_error(Symbol cur_token){
                
                System.out.println("Error sintactico");       
        }
        */
        protected int error_sync_size() {
		return 1;
	}
        public List<String> getErrorsList(){
	        return errorsList
	        ;
	}

:}

terminal ME_Q,MA_Q,ADM,SS,FS,SSS,FSS,COM,D_DOT,C_A,C_C,L_A,L_C,CR_U,USER,PASS,FECHA,ASIGNACION,ASIGNACION_ESP,ASIGNACION_NUM,CREDEN_USER,PARAMS_COMP,
        MO_U,DEL_U,LOG_U,NEW_F,DEL_F,MO_F,ADD_C,DEL_C,MO_C,DATE,
        USER_ANT,USER_NEW,PASS_NEW,FECHA_MOD,ID,TITLE,NAME,THEME,USER_CRE,NAME_CAMP,FORM,
        CLASS,IND,TEXT_VIEW,ALI,REQUE,OPTION,FILAS,COLM,URL,PARAMS_FORM,CAMP_TEXT,TEXT_AREA,CHECK,RADIO,FILE,IMG,COMBO,BOTON,CENT,IZQ,DER,JUST,
        NOT,YES,ASIG_ID,DES,MJS,SR,FR,ERL,ERS,MJSU,SCR,FCR,CONSULT_DATA,CONSULT,NUM_CONSULT;

non terminal inicio,contenido,type_s,type_s3,contenido1,cont_CR_U,cont_CR_U1,cont_CR_U2,cont_CR_U3,cont_CR_U1_2,cont_CR_U1_3,cont_CR_U2_2,cont_CR_U2_3,
                cont_CR_U3_2,cont_CR_U3_3,parametros,parametros2,
                paramsMO_U,paramsDEL_U,paramsNEW_F,paramsDEL_F,paramsMO_F,paramsADD_C,paramsDEL_C,paramsMO_C,
                paramsMO_U2,contMO_U,contMO_U1,contMO_U2,contMO_U3,contMO_U4,contMO_U5,contMO_U6,contMO_U7,contMO_U8,
                contMO_U10,contMO_U11,contMO_U12,contMO_U13,contMO_U14,contMO_U15,
                contDEL_U,paramsDEL_U2,contNEW_F,paramsNEW_F2,
                contNEW_F1,contNEW_F2,contNEW_F3,contNEW_F4,contNEW_F5,contNEW_F6,contNEW_F7,contNEW_F8,
                contNEW_F9,contNEW_F10,contNEW_F11,contNEW_F12,contNEW_F13,contNEW_F14,contNEW_F15,contNEW_F16,
                contNEW_F17,contNEW_F18,contNEW_F19,contNEW_F20,contNEW_F21,contNEW_F22,contNEW_F23,contNEW_F24,
                contNEW_F25,contNEW_F26,contNEW_F27,contNEW_F28,contNEW_F29,contNEW_F30,contNEW_F31,contNEW_F32,
                contNEW_F33,contNEW_F34,contNEW_F35,contNEW_F36,contNEW_F37,contNEW_F38,contNEW_F39,contNEW_F40,
                contNEW_F41,contNEW_F42,contNEW_F43,contNEW_F44,contNEW_F45,contNEW_F46,contNEW_F47,contNEW_F48,
                contNEW_F49,contNEW_F50,contNEW_F51,contNEW_F52,contNEW_F53,contNEW_F54,contNEW_F55,contNEW_F56,
                contNEW_F57,contNEW_F58,contNEW_F59,contNEW_F60,contNEW_F61,contNEW_F62,
                paramsDEL_F2,contDEL_F,paramsMO_F2,contMO_F,contMO_F1,contMO_F2,contMO_F3,contMO_F4,contMO_F5,
                contMO_F6,contMO_F7,contMO_F8,contMO_F9,contMO_F10,contMO_F11,contMO_F12,contMO_F13,contMO_F14,
                paramsDEL_C2,contDEL_C,contDEL_C1,contDEL_C2,type_s2,paramsLOG_U,contLOG_U,contLOG_U1,contLOG_U2,
                paramsADD_C2,contADD_C,contADD_C1,contADD_C_1,contADD_C_2,contADD_C2,paramsMO_C2,contMO_C,
                contMO_C1,contMO_C2,contMO_C_1,contMO_C_2,var_ASIGNACION,
                contRes,tipoR,paramsERL,continuacion,paramsERS,paramsMJS,contMJ,paramsERL2,
                paramsERS2,paramsMJS2,inicio2,paramsCONSULT_DATA,contCONSULT_DATA,contCONSULT_DATA1,paramsCONSULT_DATA2,var_ASIGNACION_PASS;

start with inicio;

inicio  ::=     SSS contenido FSS
        |       SCR contRes FCR
        |       ME_Q ADM inicio2
        |       error
        ;

inicio2 ::=     SS D_DOT type_s2
        |       SR D_DOT type_s3
        |       error
        ;

contRes ::=     ME_Q ADM SR D_DOT tipoR
        |       error
        ;

tipoR   ::=     ERL MA_Q L_A DES D_DOT C_A paramsERL C_C L_C ME_Q FR ADM MA_Q continuacion
        |       ERS MA_Q L_A DES D_DOT C_A paramsERS C_C L_C ME_Q FR ADM MA_Q continuacion
        |       MJSU MA_Q L_A DES D_DOT C_A paramsMJS C_C L_C ME_Q FR ADM MA_Q continuacion
        |       error
        ;

continuacion    ::=     contRes
                |
                ;

contenido       ::=     ME_Q ADM SS D_DOT type_s
                |       error
                ;

contenido1      ::=     contenido
                |
                ;

type_s ::=      CR_U MA_Q L_A CREDEN_USER D_DOT C_A parametros:e1 C_C L_C ME_Q FS ADM MA_Q contenido1
        {:
                if(e1!=null){
                    int tam = ((List<Object>)e1).size();
                    for (int i = 0 ; i < tam; i++) {
                        instrucciones.add(((List<Object>)e1).get(i));
                    }
                }
        :}
        |       MO_U MA_Q L_A CREDEN_USER D_DOT C_A paramsMO_U:e1 C_C L_C ME_Q FS ADM MA_Q contenido1
        {:
                if(e1!=null){
                    int tam = ((List<Object>)e1).size();
                    for (int i = 0; i <tam; i++) {
                        instrucciones.add(((List<Object>)e1).get(i));
                    }
                }
        :}
        |       DEL_U MA_Q L_A CREDEN_USER D_DOT C_A paramsDEL_U:e1 C_C L_C ME_Q FS ADM MA_Q contenido1
        {:
                if(e1!=null){
                    int tam = ((List<Object>)e1).size();
                    for (int i = 0 ; i < tam; i++) {
                        instrucciones.add(((List<Object>)e1).get(i));
                    }
                }
        :}
        |       NEW_F MA_Q L_A PARAMS_FORM D_DOT C_A paramsNEW_F:e1 C_C L_C ME_Q FS ADM MA_Q contenido1
        {:
                if(e1!=null){
                    int tam = ((List<Object>)e1).size();
                    for (int i = 0 ; i < tam; i++) {
                        instrucciones.add(((List<Object>)e1).get(i));
                    }
                }
        :}
        |       DEL_F MA_Q L_A PARAMS_FORM D_DOT C_A paramsDEL_F:e1 C_C L_C ME_Q FS ADM MA_Q contenido1
        {:
                if(e1!=null){
                    int tam = ((List<Object>)e1).size();
                    for (int i = 0 ; i < tam; i++) {
                        instrucciones.add(((List<Object>)e1).get(i));
                    }
                }
        :}
        |       MO_F MA_Q L_A PARAMS_FORM D_DOT C_A paramsMO_F:e1 C_C L_C ME_Q FS ADM MA_Q contenido1
        {:
                if(e1!=null){
                    int tam = ((List<Object>)e1).size();
                    for (int i = 0 ; i < tam; i++) {
                        instrucciones.add(((List<Object>)e1).get(i));
                    }
                }
        :}
        |       ADD_C MA_Q L_A PARAMS_COMP D_DOT C_A paramsADD_C:e1 C_C L_C ME_Q FS ADM MA_Q contenido1
        {:
                if(e1!=null){
                    int tam = ((List<Object>)e1).size();
                    for (int i = 0 ; i < tam; i++) {
                        instrucciones.add(((List<Object>)e1).get(i));
                    }
                }
        :}
        |       DEL_C MA_Q L_A PARAMS_COMP D_DOT C_A paramsDEL_C:e1 C_C L_C ME_Q FS ADM MA_Q contenido1
        {:
                if(e1!=null){
                    int tam = ((List<Object>)e1).size();
                    for (int i = 0 ; i < tam; i++) {
                        instrucciones.add(((List<Object>)e1).get(i));
                    }
                }
        :}
        |       MO_C MA_Q L_A PARAMS_COMP D_DOT C_A paramsMO_C:e1 C_C L_C ME_Q FS ADM MA_Q contenido1
        {:
                if(e1!=null){
                    int tam = ((List<Object>)e1).size();
                    for (int i = 0 ; i < tam; i++) {
                        instrucciones.add(((List<Object>)e1).get(i));
                    }
                }
        :}
        |       CONSULT_DATA MA_Q L_A CONSULT D_DOT C_A paramsCONSULT_DATA C_C L_C ME_Q FS ADM MA_Q contenido1
        |       error
        ;

type_s2 ::=     CR_U MA_Q L_A CREDEN_USER D_DOT C_A parametros:e1 C_C L_C ME_Q FS ADM MA_Q
        {:
                if(e1!=null){
                    int tam = ((List<Object>)e1).size();
                    for (int i = 0 ; i < tam; i++) {
                        instrucciones.add(((List<Object>)e1).get(i));
                    }
                }
        :}
        |       LOG_U MA_Q L_A CREDEN_USER D_DOT C_A paramsLOG_U C_C L_C ME_Q FS ADM MA_Q
        |       MO_U MA_Q L_A CREDEN_USER D_DOT C_A paramsMO_U:e1 C_C L_C ME_Q FS ADM MA_Q 
        {:
                if(e1!=null){
                    int tam = ((List<Object>)e1).size();
                    for (int i = 0 ; i < tam; i++) {
                        instrucciones.add(((List<Object>)e1).get(i));
                    }
                }
        :}
        |       DEL_U MA_Q L_A CREDEN_USER D_DOT C_A paramsDEL_U:e1 C_C L_C ME_Q FS ADM MA_Q 
        {:
                if(e1!=null){
                    int tam = ((List<Object>)e1).size();
                    for (int i = 0 ; i < tam; i++) {
                        instrucciones.add(((List<Object>)e1).get(i));
                    }
                }
        :}
        |       NEW_F MA_Q L_A PARAMS_FORM D_DOT C_A paramsNEW_F:e1 C_C L_C ME_Q FS ADM MA_Q
        {:
                if(e1!=null){
                    int tam = ((List<Object>)e1).size();
                    for (int i = 0 ; i < tam; i++) {
                        instrucciones.add(((List<Object>)e1).get(i));
                    }
                }
        :} 
        |       DEL_F MA_Q L_A PARAMS_FORM D_DOT C_A paramsDEL_F:e1 C_C L_C ME_Q FS ADM MA_Q 
        {:
                if(e1!=null){
                    int tam = ((List<Object>)e1).size();
                    for (int i = 0 ; i < tam; i++) {
                        instrucciones.add(((List<Object>)e1).get(i));
                    }
                }
        :}
        |       MO_F MA_Q L_A PARAMS_FORM D_DOT C_A paramsMO_F:e1 C_C L_C ME_Q FS ADM MA_Q 
        {:
                if(e1!=null){
                    int tam = ((List<Object>)e1).size();
                    for (int i = 0 ; i < tam; i++) {
                        instrucciones.add(((List<Object>)e1).get(i));
                    }
                }
        :}
        |       ADD_C MA_Q L_A PARAMS_COMP D_DOT C_A paramsADD_C:e1 C_C L_C ME_Q FS ADM MA_Q 
        {:
                if(e1!=null){
                    int tam = ((List<Object>)e1).size();
                    for (int i = 0 ; i < tam; i++) {
                        instrucciones.add(((List<Object>)e1).get(i));
                    }
                }
        :}
        |       DEL_C MA_Q L_A PARAMS_COMP D_DOT C_A paramsDEL_C:e1 C_C L_C ME_Q FS ADM MA_Q 
        {:
                if(e1!=null){
                    int tam = ((List<Object>)e1).size();
                    for (int i = 0 ; i < tam; i++) {
                        instrucciones.add(((List<Object>)e1).get(i));
                    }
                }
        :}
        |       MO_C MA_Q L_A PARAMS_COMP D_DOT C_A paramsMO_C:e1 C_C L_C ME_Q FS ADM MA_Q
        {:
                if(e1!=null){
                    int tam = ((List<Object>)e1).size();
                    for (int i = 0 ; i < tam; i++) {
                        instrucciones.add(((List<Object>)e1).get(i));
                    }
                }
        :}
        |       CONSULT_DATA MA_Q L_A CONSULT D_DOT C_A paramsCONSULT_DATA:e1 C_C L_C ME_Q FS ADM MA_Q
        |       error
        ;

type_s3 ::=     ERL MA_Q L_A DES D_DOT C_A paramsERL C_C L_C ME_Q FR ADM MA_Q 
        |       ERS MA_Q L_A DES D_DOT C_A paramsERS C_C L_C ME_Q FR ADM MA_Q
        |       MJSU MA_Q L_A DES D_DOT C_A paramsMJS C_C L_C ME_Q FR ADM MA_Q
        |       error
        ;

//PRODUCCIONES PARA ASIGNACION DE VALOR A PARAMETRO

var_ASIGNACION  ::=     ASIGNACION:e1
                {:
                        RESULT = e1;
                :}
                |       ASIGNACION_ESP:e1
                {:
                        RESULT = e1;
                :}
                |       ASIGNACION_NUM:e1
                {:
                        RESULT = e1;
                :}
                |       error
                ;

var_ASIGNACION_PASS     ::=     ASIGNACION:e1
                        {:
                                RESULT = e1;
                        :}
                        |       ASIGNACION_NUM:e1
                        {:
                                RESULT = e1;
                        :}
                        |       error
                        ;

//PRODUCCIONES PARA LA CONSULTA DE DATOS
paramsCONSULT_DATA      ::=     L_A contCONSULT_DATA:e1 L_C paramsCONSULT_DATA2:e2
                        |       error
                        ;

paramsCONSULT_DATA2     ::=     COM paramsCONSULT_DATA:e1
                        |
                        |       error
                        ;

contCONSULT_DATA        ::=     NUM_CONSULT D_DOT var_ASIGNACION:e1 contCONSULT_DATA1:e2       
                        |       error
                        ;

contCONSULT_DATA1       ::=     COM contCONSULT_DATA
                        |
                        |       error
                        ;
//PRODUCCIONES PARA LOGEAR UN USUARIO

paramsLOG_U     ::=      L_A contLOG_U:e1 L_C
                {:
                        logUser = ((e1 == null)?null:(usuario)e1);
                :}
                | error
                ;

contLOG_U       ::=     USER D_DOT ASIGNACION:e1 contLOG_U1:e2
                {:
                        RESULT = new usuario(((token)e1).getLexeme(),((e2 == null)? null:((contenedorResultado)e2).getAsignacion()), "");
                :}
                |       PASS D_DOT var_ASIGNACION_PASS:e1 contLOG_U2:e2
                {:      
                        if(e1!=null){
                                RESULT = new usuario(((e2 == null)? null:((contenedorResultado)e2).getAsignacion()), ((token)e1).getLexeme(), "");
                        }
                :}
                | error
                ;



contLOG_U1      ::=     COM PASS D_DOT var_ASIGNACION_PASS:e1
                {:
                        if(e1!=null){
                                RESULT = new contenedorResultado("PASSWORD", ((token)e1).getLexeme());
                        }
                :}
                | error
                ;

contLOG_U2      ::=     COM USER D_DOT ASIGNACION:e1       
                {:
                        //logUser.setUser(((token)e1).getLexeme());
                        RESULT = new contenedorResultado("USER", ((token)e1).getLexeme());
                :}
                | error
                ;


//PRODUCCIONES PARA CREAR UN USUARIO
parametros      ::=     L_A cont_CR_U:e1 L_C parametros2:e2
                {:
                        if(e1!=null){
                                ((usuario)e1).setAccion("CREAR_USUARIO");
                                //instrucciones.add((usuario)e1);
                                //createUser.add((usuario)e1);
                                if(e2!=null){
                                        ((List<Object>)e2).add(e1);
                                        RESULT = e2;
                                }
                        }
                :}
                |       error
                ;

parametros2     ::=     COM parametros:e1
                {:
                        RESULT = e1;
                :}
                |
                {:
                        RESULT = new ArrayList<Object>();
                :}
                |       error
                ;

cont_CR_U       ::=     USER D_DOT ASIGNACION:e1 cont_CR_U1:e2
                {:
                        if(e2!=null){
                                ((usuario)e2).setUser(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       PASS D_DOT var_ASIGNACION_PASS:e1 cont_CR_U2:e2
                {:
                        if(e2!=null&&e1!=null){
                                ((usuario)e2).setPass(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       FECHA D_DOT DATE:e1 cont_CR_U3:e2
                {:
                        if(e2!=null){
                                ((usuario)e2).setFecha(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;

cont_CR_U1      ::=     COM PASS D_DOT var_ASIGNACION_PASS:e1 cont_CR_U1_2:e2
                {:
                        if(e2!=null&&e1!=null){
                                ((usuario)e2).setPass(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM FECHA D_DOT DATE:e1 cont_CR_U1_3:e2
                {:
                        if(e2!=null){
                                ((usuario)e2).setFecha(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;

cont_CR_U1_2    ::=     COM FECHA D_DOT DATE:e1
                {:
                        RESULT = new usuario("","",((token)e1).getLexeme());
                :}
                |
                {:
                        RESULT = new usuario("","","");
                :}
                |       error
                ;

cont_CR_U1_3    ::=     COM PASS D_DOT var_ASIGNACION_PASS:e1
                {:
                        if(e1!=null){
                                RESULT = new usuario("",((token)e1).getLexeme(),"");
                        }
                :}
                |       error
                ;

cont_CR_U2      ::=     COM USER D_DOT ASIGNACION:e1 cont_CR_U2_2:e2
                {:
                        if(e2!=null){
                                ((usuario)e2).setUser(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM FECHA D_DOT DATE:e1 cont_CR_U2_3:e2
                {:      
                        if(e2!=null){
                                ((usuario)e2).setFecha(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;

cont_CR_U2_2    ::=     COM FECHA D_DOT DATE:e1
                {:
                        RESULT = new usuario("","",((token)e1).getLexeme());
                :}
                |
                {:
                        RESULT = new usuario("","","");
                :}
                |       error
                ;
cont_CR_U2_3    ::=     COM USER D_DOT ASIGNACION:e1
                {:
                        RESULT = new usuario(((token)e1).getLexeme(),"","");
                :}
                |       error
                ;

cont_CR_U3      ::=     COM USER D_DOT ASIGNACION:e1 cont_CR_U3_2:e2
                {:
                        if(e2!=null){
                                ((usuario)e2).setUser(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM PASS D_DOT var_ASIGNACION_PASS:e1 cont_CR_U3_3:e2
                {:
                        if(e2!=null&&e1!=null){
                                ((usuario)e2).setPass(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;

cont_CR_U3_2    ::=     COM PASS D_DOT var_ASIGNACION_PASS:e1
                {:
                        if(e1!=null){
                                RESULT = new usuario("",((token)e1).getLexeme(),"");
                        }
                :}
                |       error
                ;

cont_CR_U3_3    ::=     COM USER D_DOT ASIGNACION:e1
                {:
                        RESULT = new usuario(((token)e1).getLexeme(),"","");
                :}
                |       error
                ;

//PRODUCCIONES PARA LA MODIFICACION DE UN USAURIO
paramsMO_U      ::=     L_A contMO_U:e1 L_C paramsMO_U2:e2
                {:
                        if(e1!=null){
                                ((userNew)e1).setAccion("MODIFICAR_USUARIO");
                                //instrucciones.add((userNew)e1);
                                //modUser.add((userNew)e1);
                                if(e2!=null){
                                        ((List<Object>)e2).add(e1);
                                        RESULT = e2;
                                }
                        }
                :}
                |       error
                ;

paramsMO_U2     ::=     COM paramsMO_U:e1
                {:
                        RESULT = e1;
                :}
                |
                {:
                        RESULT = new ArrayList<Object>();
                :}
                |       error
                ;

contMO_U        ::=     USER_ANT D_DOT ASIGNACION:e1 contMO_U1:e2
                {:
                        if(e2!=null){
                                ((userNew)e2).setUser(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       USER_NEW D_DOT ASIGNACION:e1 contMO_U2:e2
                {:
                        if(e2!=null){
                                ((userNew)e2).setNewUser(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       PASS_NEW D_DOT var_ASIGNACION_PASS:e1 contMO_U3:e2
                {:
                        if(e2!=null&&e1!=null){
                                ((userNew)e2).setNewPass(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       FECHA_MOD D_DOT DATE:e1 contMO_U4:e2
                {:
                        if(e2!=null){
                                ((userNew)e2).setFechaMod(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;
//-------------------------------------------------------------------
contMO_U1       ::=     COM USER_NEW D_DOT ASIGNACION:e1 contMO_U5:e2
                {:
                        if(e2!=null){
                                ((userNew)e2).setNewUser(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM PASS_NEW D_DOT var_ASIGNACION_PASS:e1 contMO_U8:e2
                {:
                        if(e2!=null&&e1!=null){
                                ((userNew)e2).setNewPass(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM FECHA_MOD D_DOT DATE:e1 contMO_U11:e2
                {:
                        if(e2!=null){
                                ((userNew)e2).setFechaMod(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;

contMO_U2       ::=     COM USER_ANT D_DOT ASIGNACION:e1 contMO_U5:e2
                {:
                        if(e2!=null){
                                ((userNew)e2).setUser(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM PASS_NEW D_DOT var_ASIGNACION_PASS:e1 contMO_U6:e2
                {:
                        if(e2!=null&&e1!=null){
                                ((userNew)e2).setNewPass(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM FECHA_MOD D_DOT DATE:e1 contMO_U7:e2
                {:
                        if(e2!=null){
                                ((userNew)e2).setFechaMod(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;

contMO_U3       ::=     COM USER_ANT D_DOT ASIGNACION:e1 contMO_U5:e2
                {:
                        if(e2!=null){
                                ((userNew)e2).setUser(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM USER_NEW D_DOT ASIGNACION:e1 contMO_U6:e2
                {:
                        if(e2!=null){
                                ((userNew)e2).setNewUser(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM FECHA_MOD D_DOT DATE:e1 contMO_U10:e2
                {:
                        if(e2!=null){
                                ((userNew)e2).setFechaMod(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;

contMO_U4       ::=     COM USER_ANT D_DOT ASIGNACION:e1 contMO_U11:e2
                {:
                        if(e2!=null){
                                ((userNew)e2).setUser(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM USER_NEW D_DOT ASIGNACION:e1 contMO_U7:e2
                {:
                        if(e2!=null){
                                ((userNew)e2).setNewUser(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM PASS_NEW D_DOT var_ASIGNACION_PASS:e1 contMO_U10:e2
                {:
                        if(e2!=null&&e1!=null){
                                ((userNew)e2).setNewPass(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;
//----------------------------------------------------
contMO_U5       ::=     COM PASS_NEW D_DOT var_ASIGNACION_PASS:e1 contMO_U15:e2
                {:
                        if(e2!=null&&e1!=null){
                                ((userNew)e2).setNewPass(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM FECHA_MOD D_DOT DATE:e1 contMO_U14:e2
                {:
                        if(e2!=null){
                                ((userNew)e2).setFechaMod(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;

contMO_U6       ::=     COM USER_ANT D_DOT ASIGNACION:e1 contMO_U15:e2
                {:
                        if(e2!=null){
                                ((userNew)e2).setUser(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM FECHA_MOD D_DOT DATE:e1 contMO_U12:e2
                {:
                        if(e2!=null){
                                ((userNew)e2).setFechaMod(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;

contMO_U7       ::=     COM USER_ANT D_DOT ASIGNACION:e1 contMO_U14:e2
                {:
                        if(e2!=null){
                                ((userNew)e2).setUser(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM PASS_NEW D_DOT var_ASIGNACION_PASS:e1 contMO_U12:e2
                {:
                        if(e2!=null&&e1!=null){
                                ((userNew)e2).setNewPass(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;

contMO_U8       ::=     COM PASS_NEW D_DOT var_ASIGNACION_PASS:e1 contMO_U15:e2
                {:
                        if(e2!=null&&e1!=null){
                                ((userNew)e2).setNewPass(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM FECHA_MOD D_DOT DATE:e1 contMO_U14:e2
                {:
                        if(e2!=null){
                                ((userNew)e2).setFechaMod(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;

contMO_U10      ::=     COM USER_ANT D_DOT ASIGNACION:e1 contMO_U13:e2
                {:
                        if(e2!=null){
                                ((userNew)e2).setUser(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM USER_NEW D_DOT ASIGNACION:e1 contMO_U12:e2
                {:
                        if(e2!=null){
                                ((userNew)e2).setNewUser(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;

contMO_U11      ::=     COM USER_NEW D_DOT ASIGNACION:e1 contMO_U14:e2
                {:
                        if(e2!=null){
                                ((userNew)e2).setNewUser(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM PASS_NEW D_DOT var_ASIGNACION_PASS:e1 contMO_U13:e2
                {:
                        if(e2!=null&&e1!=null){
                                ((userNew)e2).setNewPass(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;
//---------------------------------------------------------
contMO_U12      ::=     COM USER_ANT D_DOT ASIGNACION:e1
                {:
                        RESULT = new userNew("","","",((token)e1).getLexeme(), "");
                :}
                |       error
                ;
contMO_U13      ::=     COM USER_NEW D_DOT ASIGNACION:e1
                {:
                        RESULT = new userNew(((token)e1).getLexeme(),"","", "", "");
                :}
                |       error
                ;
contMO_U14      ::=     COM PASS_NEW D_DOT var_ASIGNACION_PASS:e1
                {:
                        if(e1!=null){
                                RESULT = new userNew("",((token)e1).getLexeme(),"", "", "");
                        }
                :}
                |       error
                ;
contMO_U15      ::=     COM FECHA_MOD D_DOT DATE:e1
                {:
                        RESULT = new userNew("", "",((token)e1).getLexeme(), "", "");
                :}
                |
                {:
                        RESULT = new userNew("", "", "", "", "");
                :}
                |       error
                ;

//PRODUCCIONES PARA LA ELIMINACION DE UN USUARIO
paramsDEL_U     ::=     L_A contDEL_U:e1 L_C paramsDEL_U2:e2
                {:
                        if(e1!=null){
                                ((usuario)e1).setAccion("ELIMINAR_USUARIO");
                                //instrucciones.add(e1);
                                //delUser.add(new usuario(((contenedorResultado)e1).getAsignacion(), "", ""));
                                if(e2!=null){
                                        ((List<Object>)e2).add(e1);
                                        RESULT = e2;
                                }
                        }
                :}
                |       error
                ;
paramsDEL_U2    ::=     COM paramsDEL_U:e1
                {:
                        RESULT = e1;
                :}
                |
                {:
                        RESULT = new ArrayList<Object>();
                :}
                |       error
                ;

contDEL_U       ::=     USER D_DOT ASIGNACION:e1
                {:
                        RESULT = new usuario(((token)e1).getLexeme(),"","");
                :}
                |       error
                ;
//PRODUCCIONES PARA UN NUEVO FORMULARIO
paramsNEW_F     ::=     L_A contNEW_F:e1 L_C paramsNEW_F2:e2
                {:
                        if(e1!=null){
                                ((formulario)e1).setAccion("NUEVO_FORMULARIO");
                                //instrucciones.add(e1);
                                //newForms.add((formulario)e1);
                                if(e2!=null){
                                        ((List<Object>)e2).add(e1);
                                        RESULT = e2;
                                }
                        }
                :}
                |       error
                ;


paramsNEW_F2    ::=     COM paramsNEW_F:e1
                {:
                        RESULT =e1;
                :}
                | 
                {:
                        RESULT = new ArrayList<Object>();
                :}
                |       error
                ;
//-----------------------------------------------------
contNEW_F       ::=     ID D_DOT ASIG_ID:e1 contNEW_F1:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setId(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       TITLE D_DOT var_ASIGNACION:e1 contNEW_F2:e2
                {:
                        if(e2!=null){
                                if(e1!=null){
                                        ((formulario)e2).setTitulo(((token)e1).getLexeme());
                                        RESULT = e2;
                                }
                        }
                :}
                |       NAME D_DOT ASIGNACION:e1 contNEW_F3:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setNombre(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       THEME D_DOT ASIGNACION:e1 contNEW_F4:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setTema(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       USER_CRE D_DOT ASIGNACION:e1 contNEW_F5:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setUser(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       FECHA D_DOT DATE:e1 contNEW_F6:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setFecha(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;
//-----------------------------------------------------
contNEW_F1      ::=     COM TITLE D_DOT var_ASIGNACION:e1 contNEW_F7:e2
                {:
                        if(e2!=null){
                                if(e1!=null){
                                        ((formulario)e2).setTitulo(((token)e1).getLexeme());
                                        RESULT = e2;
                                }
                        }
                :}
                |       COM NAME D_DOT ASIGNACION:e1 contNEW_F8:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setNombre(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM THEME D_DOT ASIGNACION:e1 contNEW_F9:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setTema(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM USER_CRE D_DOT ASIGNACION:e1 contNEW_F10:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setUser(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM FECHA D_DOT DATE:e1 contNEW_F11:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setFecha(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;

contNEW_F2      ::=     COM ID D_DOT ASIG_ID:e1 contNEW_F7:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setId(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM NAME D_DOT ASIGNACION:e1 contNEW_F12:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setNombre(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM THEME D_DOT ASIGNACION:e1 contNEW_F13:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setTema(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM USER_CRE D_DOT ASIGNACION:e1 contNEW_F14:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setUser(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM FECHA D_DOT DATE:e1 contNEW_F15:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setFecha(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;

contNEW_F3      ::=     COM ID D_DOT ASIG_ID:e1 contNEW_F8:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setId(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM TITLE D_DOT var_ASIGNACION:e1 contNEW_F12:e2
                {:
                        if(e2!=null){
                                if(e1!=null){
                                        ((formulario)e2).setTitulo(((token)e1).getLexeme());
                                        RESULT = e2;
                                }
                        }
                :}
                |       COM THEME D_DOT ASIGNACION:e1 contNEW_F16:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setTema(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM USER_CRE D_DOT ASIGNACION:e1 contNEW_F17:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setUser(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM FECHA D_DOT DATE:e1 contNEW_F18:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setFecha(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;

contNEW_F4      ::=     COM ID D_DOT ASIG_ID:e1 contNEW_F9:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setId(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM TITLE D_DOT var_ASIGNACION:e1 contNEW_F13:e2
                {:
                        if(e2!=null){
                                if(e1!=null){
                                        ((formulario)e2).setTitulo(((token)e1).getLexeme());
                                        RESULT = e2;
                                }
                        }
                :}
                |       COM NAME D_DOT ASIGNACION:e1 contNEW_F16:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setNombre(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM USER_CRE D_DOT ASIGNACION:e1 contNEW_F19:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setUser(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM FECHA D_DOT DATE:e1 contNEW_F20:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setFecha(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;

contNEW_F5      ::=     COM ID D_DOT ASIG_ID:e1 contNEW_F10:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setId(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM TITLE D_DOT var_ASIGNACION:e1 contNEW_F14:e2
                {:
                        if(e2!=null){
                                if(e1!=null){
                                        ((formulario)e2).setTitulo(((token)e1).getLexeme());
                                        RESULT = e2;
                                }
                        }
                :}
                |       COM NAME D_DOT ASIGNACION:e1 contNEW_F17:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setNombre(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM THEME D_DOT ASIGNACION:e1 contNEW_F19:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setTema(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM FECHA D_DOT DATE:e1 contNEW_F21:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setFecha(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;

contNEW_F6      ::=     COM ID D_DOT ASIG_ID:e1 contNEW_F11:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setId(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM TITLE D_DOT var_ASIGNACION:e1 contNEW_F15:e2
                {:
                        if(e2!=null){
                                if(e1!=null){
                                        ((formulario)e2).setTitulo(((token)e1).getLexeme());
                                        RESULT = e2;
                                }
                        }
                :}
                |       COM NAME D_DOT ASIGNACION:e1 contNEW_F18:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setNombre(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM THEME D_DOT ASIGNACION:e1 contNEW_F20:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setTema(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM USER_CRE D_DOT ASIGNACION:e1 contNEW_F21:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setUser(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;
//------------------------------------------------------------------
contNEW_F7      ::=     COM NAME D_DOT ASIGNACION:e1 contNEW_F22:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setNombre(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM THEME D_DOT ASIGNACION:e1 contNEW_F23:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setTema(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM USER_CRE D_DOT ASIGNACION:e1 contNEW_F24:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setUser(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM FECHA D_DOT DATE:e1 contNEW_F25:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setFecha(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;

contNEW_F8      ::=     COM TITLE D_DOT var_ASIGNACION:e1 contNEW_F22:e2
                {:
                        if(e2!=null){
                                if(e1!=null){
                                        ((formulario)e2).setTitulo(((token)e1).getLexeme());
                                        RESULT = e2;
                                }
                        }
                :}
                |       COM THEME D_DOT ASIGNACION:e1 contNEW_F26:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setTema(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM USER_CRE D_DOT ASIGNACION:e1 contNEW_F27:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setUser(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM FECHA D_DOT DATE:e1 contNEW_F28:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setFecha(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;

contNEW_F9      ::=     COM TITLE D_DOT var_ASIGNACION:e1 contNEW_F23:e2
                {:
                        if(e2!=null){
                                if(e1!=null){
                                        ((formulario)e2).setTitulo(((token)e1).getLexeme());
                                        RESULT = e2;
                                }
                        }
                :}
                |       COM NAME D_DOT ASIGNACION:e1 contNEW_F26:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setNombre(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM USER_CRE D_DOT ASIGNACION:e1 contNEW_F29:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setUser(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM FECHA D_DOT DATE:e1 contNEW_F30:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setFecha(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;

contNEW_F10     ::=     COM TITLE D_DOT var_ASIGNACION:e1 contNEW_F24:e2
                {:
                        if(e2!=null){
                                if(e1!=null){
                                        ((formulario)e2).setTitulo(((token)e1).getLexeme());
                                        RESULT = e2;
                                }
                        }
                :}
                |       COM NAME D_DOT ASIGNACION:e1 contNEW_F27:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setNombre(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM THEME D_DOT ASIGNACION:e1 contNEW_F29:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setTema(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM FECHA D_DOT DATE:e1 contNEW_F31:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setFecha(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;

contNEW_F11     ::=     COM TITLE D_DOT var_ASIGNACION:e1 contNEW_F25:e2
                {:
                        if(e2!=null){
                                if(e1!=null){
                                        ((formulario)e2).setTitulo(((token)e1).getLexeme());
                                        RESULT = e2;
                                }
                        }
                :}
                |       COM NAME D_DOT ASIGNACION:e1 contNEW_F28:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setNombre(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM THEME D_DOT ASIGNACION:e1 contNEW_F30:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setTema(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM USER_CRE D_DOT ASIGNACION:e1 contNEW_F31:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setUser(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;

contNEW_F12     ::=     COM ID D_DOT ASIG_ID:e1 contNEW_F22:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setUser(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM THEME D_DOT ASIGNACION:e1 contNEW_F32:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setTema(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM USER_CRE D_DOT ASIGNACION:e1 contNEW_F33:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setUser(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM FECHA D_DOT DATE:e1 contNEW_F34:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setFecha(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;

contNEW_F13     ::=     COM ID D_DOT ASIG_ID:e1 contNEW_F23:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setId(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM NAME D_DOT ASIGNACION:e1 contNEW_F32:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setNombre(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM USER_CRE D_DOT ASIGNACION:e1 contNEW_F35:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setUser(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM FECHA D_DOT DATE:e1 contNEW_F36:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setFecha(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;

contNEW_F14     ::=     COM ID D_DOT ASIG_ID:e1 contNEW_F24:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setId(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM NAME D_DOT ASIGNACION:e1 contNEW_F33:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setNombre(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM THEME D_DOT ASIGNACION:e1 contNEW_F35:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setTema(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM FECHA D_DOT DATE:e1 contNEW_F37:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setFecha(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;

contNEW_F15     ::=     COM ID D_DOT ASIG_ID:e1 contNEW_F25:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setId(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM NAME D_DOT ASIGNACION:e1 contNEW_F34:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setNombre(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM THEME D_DOT ASIGNACION:e1 contNEW_F36:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setTema(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM USER_CRE D_DOT ASIGNACION:e1 contNEW_F37:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setUser(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;

contNEW_F16     ::=     COM ID D_DOT ASIG_ID:e1 contNEW_F26:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setId(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM TITLE D_DOT var_ASIGNACION:e1 contNEW_F32:e2
                {:
                        if(e2!=null){
                                if(e1!=null){
                                        ((formulario)e2).setTitulo(((token)e1).getLexeme());
                                        RESULT = e2;
                                }
                        }
                :}
                |       COM USER_CRE D_DOT ASIGNACION:e1 contNEW_F38:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setUser(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM FECHA D_DOT DATE:e1 contNEW_F39:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setFecha(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;

contNEW_F17     ::=     COM ID D_DOT ASIG_ID:e1 contNEW_F27:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setId(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM TITLE D_DOT var_ASIGNACION:e1 contNEW_F33:e2
                {:
                        if(e2!=null){
                                if(e1!=null){
                                        ((formulario)e2).setTitulo(((token)e1).getLexeme());
                                        RESULT = e2;
                                }
                        }
                :}
                |       COM THEME D_DOT ASIGNACION:e1 contNEW_F38:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setTema(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM FECHA D_DOT DATE:e1 contNEW_F40:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setFecha(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;

contNEW_F18     ::=     COM ID D_DOT ASIG_ID:e1 contNEW_F28:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setId(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM TITLE D_DOT var_ASIGNACION:e1 contNEW_F34:e2
                {:
                        if(e2!=null){
                                if(e1!=null){
                                        ((formulario)e2).setTitulo(((token)e1).getLexeme());
                                        RESULT = e2;
                                }
                        }
                :}
                |       COM THEME D_DOT ASIGNACION:e1 contNEW_F39:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setTema(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM USER_CRE D_DOT ASIGNACION:e1 contNEW_F40:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setUser(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;

contNEW_F19     ::=     COM ID D_DOT ASIG_ID:e1 contNEW_F29:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setId(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM TITLE D_DOT var_ASIGNACION:e1 contNEW_F35:e2
                {:
                        if(e2!=null){
                                if(e1!=null){
                                        ((formulario)e2).setTitulo(((token)e1).getLexeme());
                                        RESULT = e2;
                                }
                        }
                :}
                |       COM NAME D_DOT ASIGNACION:e1 contNEW_F38:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setNombre(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM FECHA D_DOT DATE:e1 contNEW_F41:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setFecha(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;

contNEW_F20     ::=     COM ID D_DOT ASIG_ID:e1 contNEW_F30:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setId(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM TITLE D_DOT var_ASIGNACION:e1 contNEW_F36:e2
                {:
                        if(e2!=null){
                                if(e1!=null){
                                        ((formulario)e2).setTitulo(((token)e1).getLexeme());
                                        RESULT = e2;
                                }
                        }
                :}
                |       COM NAME D_DOT ASIGNACION:e1 contNEW_F39:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setNombre(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM USER_CRE D_DOT ASIGNACION:e1 contNEW_F41:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setUser(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;

contNEW_F21     ::=     COM ID D_DOT ASIG_ID:e1 contNEW_F31:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setId(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM TITLE D_DOT var_ASIGNACION:e1 contNEW_F37:e2
                {:
                        if(e2!=null){
                                if(e1!=null){
                                        ((formulario)e2).setTitulo(((token)e1).getLexeme());
                                        RESULT = e2;
                                }
                        }
                :}
                |       COM NAME D_DOT ASIGNACION:e1 contNEW_F40:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setNombre(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM THEME D_DOT ASIGNACION:e1 contNEW_F41:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setTema(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;
//-------------------------------------------------------
contNEW_F22     ::=     COM THEME D_DOT ASIGNACION:e1 contNEW_F42:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setTema(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM USER_CRE D_DOT ASIGNACION:e1 contNEW_F43:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setUser(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM FECHA D_DOT DATE:e1 contNEW_F44:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setFecha(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;

contNEW_F23     ::=     COM NAME D_DOT ASIGNACION:e1 contNEW_F42:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setNombre(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM USER_CRE D_DOT ASIGNACION:e1 contNEW_F45:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setUser(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM FECHA D_DOT DATE:e1 contNEW_F46:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setFecha(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;

contNEW_F24     ::=     COM NAME D_DOT ASIGNACION:e1 contNEW_F43:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setNombre(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM THEME D_DOT ASIGNACION:e1 contNEW_F45:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setTema(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM FECHA D_DOT DATE:e1 contNEW_F47:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setFecha(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;

contNEW_F25     ::=     COM NAME D_DOT ASIGNACION:e1 contNEW_F44:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setNombre(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM THEME D_DOT ASIGNACION:e1 contNEW_F46:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setTema(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM USER_CRE D_DOT ASIGNACION:e1 contNEW_F47:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setUser(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;

contNEW_F26     ::=     COM TITLE D_DOT var_ASIGNACION:e1 contNEW_F42:e2
                {:
                        if(e2!=null){
                                if(e1!=null){
                                        ((formulario)e2).setTitulo(((token)e1).getLexeme());
                                        RESULT = e2;
                                }
                        }
                :}
                |       COM USER_CRE D_DOT ASIGNACION:e1 contNEW_F48:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setUser(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM FECHA D_DOT DATE:e1 contNEW_F49:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setFecha(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;

contNEW_F27     ::=     COM TITLE D_DOT var_ASIGNACION:e1 contNEW_F43:e2
                {:
                        if(e2!=null){
                                if(e1!=null){
                                        ((formulario)e2).setTitulo(((token)e1).getLexeme());
                                        RESULT = e2;
                                }
                        }
                :}
                |       COM THEME D_DOT ASIGNACION:e1 contNEW_F48:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setTema(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM FECHA D_DOT DATE:e1 contNEW_F50:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setFecha(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;

contNEW_F28     ::=     COM TITLE D_DOT var_ASIGNACION:e1 contNEW_F44:e2
                {:
                        if(e2!=null){
                                if(e1!=null){
                                        ((formulario)e2).setTitulo(((token)e1).getLexeme());
                                        RESULT = e2;    
                                }
                        }
                :}
                |       COM THEME D_DOT ASIGNACION:e1 contNEW_F49:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setTema(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM USER_CRE D_DOT ASIGNACION:e1 contNEW_F50:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setUser(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;

contNEW_F29     ::=     COM TITLE D_DOT var_ASIGNACION:e1 contNEW_F45:e2
                {:
                        if(e2!=null){
                                if(e1!=null){
                                        ((formulario)e2).setTitulo(((token)e1).getLexeme());
                                        RESULT = e2;
                                }
                        }
                :}
                |       COM NAME D_DOT ASIGNACION:e1 contNEW_F48:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setNombre(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM FECHA D_DOT DATE:e1 contNEW_F51:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setFecha(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;

contNEW_F30     ::=     COM TITLE D_DOT var_ASIGNACION:e1 contNEW_F46:e2
                {:
                        if(e2!=null){
                                if(e1!=null){
                                        ((formulario)e2).setTitulo(((token)e1).getLexeme());
                                        RESULT = e2;
                                }
                        }
                :}
                |       COM NAME D_DOT ASIGNACION:e1 contNEW_F49:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setNombre(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM USER_CRE D_DOT ASIGNACION:e1 contNEW_F51:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setUser(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;

contNEW_F31     ::=     COM TITLE D_DOT var_ASIGNACION:e1 contNEW_F47:e2
                {:
                        if(e2!=null){
                                if(e1!=null){
                                        ((formulario)e2).setTitulo(((token)e1).getLexeme());
                                        RESULT = e2;
                                }
                        }
                :}
                |       COM NAME D_DOT ASIGNACION:e1 contNEW_F50:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setNombre(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM THEME D_DOT ASIGNACION:e1 contNEW_F51:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setTema(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;

contNEW_F32     ::=     COM ID D_DOT ASIG_ID:e1 contNEW_F42:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setId(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM USER_CRE D_DOT ASIGNACION:e1 contNEW_F52:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setUser(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM FECHA D_DOT DATE:e1 contNEW_F53:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setFecha(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;

contNEW_F33     ::=     COM ID D_DOT ASIG_ID:e1 contNEW_F43:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setId(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM THEME D_DOT ASIGNACION:e1 contNEW_F52:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setTema(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM FECHA D_DOT DATE:e1 contNEW_F54:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setFecha(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;

contNEW_F34     ::=     COM ID D_DOT ASIG_ID:e1 contNEW_F44:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setId(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM THEME D_DOT ASIGNACION:e1 contNEW_F53:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setTema(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM USER_CRE D_DOT ASIGNACION:e1 contNEW_F54:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setUser(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;

contNEW_F35     ::=     COM ID D_DOT ASIG_ID:e1 contNEW_F45:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setId(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM NAME D_DOT ASIGNACION:e1 contNEW_F52:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setNombre(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM FECHA D_DOT DATE:e1 contNEW_F55:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setFecha(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;

contNEW_F36     ::=     COM ID D_DOT ASIG_ID:e1 contNEW_F46:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setId(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM NAME D_DOT ASIGNACION:e1 contNEW_F53:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setNombre(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM USER_CRE D_DOT ASIGNACION:e1 contNEW_F55:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setUser(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;

contNEW_F37     ::=     COM ID D_DOT ASIG_ID:e1 contNEW_F47:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setId(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM NAME D_DOT ASIGNACION:e1 contNEW_F54:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setNombre(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM THEME D_DOT ASIGNACION:e1 contNEW_F55:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setTema(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;

contNEW_F38     ::=     COM ID D_DOT ASIG_ID:e1 contNEW_F48:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setId(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM TITLE D_DOT var_ASIGNACION:e1 contNEW_F52:e2
                {:
                        if(e2!=null){
                                if(e1!=null){
                                        ((formulario)e2).setTitulo(((token)e1).getLexeme());
                                        RESULT = e2;
                                }
                        }
                :}
                |       COM FECHA D_DOT DATE:e1 contNEW_F56:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setFecha(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;

contNEW_F39     ::=     COM ID D_DOT ASIG_ID:e1 contNEW_F49:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setId(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM TITLE D_DOT var_ASIGNACION:e1 contNEW_F53:e2
                {:
                        if(e2!=null){
                                if(e1!=null){
                                        ((formulario)e2).setTitulo(((token)e1).getLexeme());
                                        RESULT = e2;
                                }
                        }
                :}
                |       COM USER_CRE D_DOT ASIGNACION:e1 contNEW_F56:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setUser(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;

contNEW_F40     ::=     COM ID D_DOT ASIG_ID:e1 contNEW_F50:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setId(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM TITLE D_DOT var_ASIGNACION:e1 contNEW_F54:e2
                {:
                        if(e2!=null){
                                if(e1!=null){
                                        ((formulario)e2).setTitulo(((token)e1).getLexeme());
                                        RESULT = e2;
                                }
                        }
                :}
                |       COM THEME D_DOT ASIGNACION:e1 contNEW_F56:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setTema(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;

contNEW_F41     ::=     COM ID D_DOT ASIG_ID:e1 contNEW_F51:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setId(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM TITLE D_DOT var_ASIGNACION:e1 contNEW_F55:e2
                {:
                        if(e2!=null){
                                if(e1!=null){
                                        ((formulario)e2).setTitulo(((token)e1).getLexeme());
                                        RESULT = e2;
                                }
                        }
                :}
                |       COM NAME D_DOT ASIGNACION:e1 contNEW_F56:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setNombre(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;
//-------------------------------------------------

contNEW_F42     ::=     COM USER_CRE D_DOT ASIGNACION:e1 contNEW_F57:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setUser(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM FECHA D_DOT DATE:e1 contNEW_F58:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setFecha(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |
                {:
                        RESULT = new formulario("","","","","","");
                :}
                |       error
                ;

contNEW_F43     ::=     COM THEME D_DOT ASIGNACION:e1 contNEW_F57:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setTema(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM FECHA D_DOT DATE:e1 contNEW_F59:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setFecha(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;

contNEW_F44     ::=     COM THEME D_DOT ASIGNACION:e1 contNEW_F58:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setTema(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM USER_CRE D_DOT ASIGNACION:e1 contNEW_F59:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setUser(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;

contNEW_F45     ::=     COM NAME D_DOT ASIGNACION:e1 contNEW_F57:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setNombre(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM FECHA D_DOT DATE:e1 contNEW_F60:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setFecha(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;

contNEW_F46     ::=     COM NAME D_DOT ASIGNACION:e1 contNEW_F58:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setNombre(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM USER_CRE D_DOT ASIGNACION:e1 contNEW_F60:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setUser(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;

contNEW_F47     ::=     COM NAME D_DOT ASIGNACION:e1 contNEW_F59:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setNombre(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM THEME D_DOT ASIGNACION:e1 contNEW_F60:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setTema(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;

contNEW_F48     ::=     COM TITLE D_DOT var_ASIGNACION:e1 contNEW_F57:e2
                {:
                        if(e2!=null){
                                if(e1!=null){
                                        ((formulario)e2).setTitulo(((token)e1).getLexeme());
                                        RESULT = e2;
                                }
                        }
                :}
                |       COM FECHA D_DOT DATE:e1 contNEW_F61:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setFecha(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;

contNEW_F49     ::=     COM TITLE D_DOT var_ASIGNACION:e1 contNEW_F58:e2
                {:
                        if(e2!=null){
                                if(e1!=null){
                                        ((formulario)e2).setTitulo(((token)e1).getLexeme());
                                        RESULT = e2;
                                }
                        }
                :}
                |       COM USER_CRE D_DOT ASIGNACION:e1 contNEW_F61:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setUser(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;

contNEW_F50     ::=     COM TITLE D_DOT var_ASIGNACION:e1 contNEW_F59:e2
                {:
                        if(e2!=null){
                                if(e1!=null){
                                        ((formulario)e2).setTitulo(((token)e1).getLexeme());
                                        RESULT = e2;
                                }
                        }
                :}
                |       COM THEME D_DOT ASIGNACION:e1 contNEW_F61:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setTema(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;

contNEW_F51     ::=     COM TITLE D_DOT var_ASIGNACION:e1 contNEW_F60:e2
                {:
                        if(e2!=null){
                                if(e1!=null){
                                        ((formulario)e2).setTitulo(((token)e1).getLexeme());
                                        RESULT = e2;
                                }
                        }
                :}
                |       COM NAME D_DOT ASIGNACION:e1 contNEW_F61:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setNombre(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;

contNEW_F52     ::=     COM ID D_DOT ASIG_ID:e1 contNEW_F57:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setId(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM FECHA D_DOT DATE:e1 contNEW_F62:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setFecha(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;

contNEW_F53     ::=     COM ID D_DOT ASIG_ID:e1 contNEW_F58:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setId(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM USER_CRE D_DOT ASIGNACION:e1 contNEW_F62:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setUser(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;

contNEW_F54     ::=     COM ID D_DOT ASIG_ID:e1 contNEW_F59:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setId(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM THEME D_DOT ASIGNACION:e1 contNEW_F62:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setTema(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;

contNEW_F55     ::=     COM ID D_DOT ASIG_ID:e1 contNEW_F60:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setId(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM NAME D_DOT ASIGNACION:e1 contNEW_F62:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setNombre(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;

contNEW_F56     ::=     COM ID D_DOT ASIG_ID:e1 contNEW_F61:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setId(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM TITLE D_DOT var_ASIGNACION:e1 contNEW_F62:e2
                {:
                        if(e2!=null){
                                if(e1!=null){
                                        ((formulario)e2).setTitulo(((token)e1).getLexeme());
                                        RESULT = e2;
                                }
                        }
                :}
                |       error
                ;
//----------------------------------------------------
contNEW_F57     ::=     COM FECHA D_DOT DATE:e1
                {:
                        RESULT = new formulario("","","","","",((token)e1).getLexeme());
                :}
                |
                {:
                        RESULT = new formulario("","","","","","");
                :}
                |       error
                ;
contNEW_F58     ::=     COM USER_CRE D_DOT ASIGNACION:e1
                {:
                        RESULT = new formulario("","","","",((token)e1).getLexeme(),"");
                :}
                |
                {:
                        RESULT = new formulario("","","","","","");
                :}
                |       error
                ;

contNEW_F59     ::=     COM THEME D_DOT ASIGNACION:e1
                {:
                        RESULT = new formulario("","","",((token)e1).getLexeme(),"","");
                :}
                |       error
                ;

contNEW_F60     ::=     COM NAME D_DOT ASIGNACION:e1
                {:
                        RESULT = new formulario("","",((token)e1).getLexeme(),"","","");
                :}
                |       error
                ;

contNEW_F61     ::=     COM TITLE D_DOT var_ASIGNACION:e1
                {:
                        if(e1!=null){
                                RESULT = new formulario("",((token)e1).getLexeme(),"","","","");
                        }
                :}
                |       error
                ;

contNEW_F62     ::=     COM ID D_DOT ASIG_ID:e1
                {:
                        RESULT = new formulario(((token)e1).getLexeme(),"","","","","");
                :}
                |       error
                ;

//PRODUCCIONES PARA ELIMINAR UN FORMULARIO

paramsDEL_F     ::=     L_A contDEL_F:e1 L_C paramsDEL_F2:e2
                {:
                        if(e1!=null){
                                ((formulario)e1).setAccion("ELIMINAR_FORMULARIO");
                                //instrucciones.add(e1);
                                //delForm.add((formulario)e1);
                                if(e2!=null){
                                        ((List<Object>)e2).add(e1);
                                        RESULT = e2;
                                }
                        }
                :}
                |       error
                ;

paramsDEL_F2    ::=     COM paramsDEL_F:e1
                {:
                        RESULT =e1;
                :}
                |
                {:
                        RESULT = new ArrayList<Object>();
                :}
                |       error
                ;

contDEL_F       ::=      ID D_DOT ASIG_ID:e1
                {:
                        RESULT = new formulario(((token)e1).getLexeme(), "", "", "", "", "");
                :}
                |       error
                ;

//PRODUCCIONES PARA MODIFICAR UN FORMULARIO

paramsMO_F      ::=     L_A contMO_F:e1 L_C paramsMO_F2:e2
                {:
                        if(e1!=null){
                                ((formulario)e1).setAccion("MODIFICAR_FORMULARIO");
                                //instrucciones.add(e1);
                                //modForm.add((formulario)e1);
                                if(e2!=null){
                                        ((List<Object>)e2).add(e1);
                                        RESULT = e2;
                                }
                        }
                :}
                |       error
                ;

paramsMO_F2      ::=     COM paramsMO_F:e1
                {:
                        RESULT =e1;
                :}
                |
                {:
                        RESULT = new ArrayList<Object>();
                :}
                |       error
                ;
//------------------------------------------------

contMO_F        ::=     ID D_DOT ASIG_ID:e1 contMO_F1:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setId(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       TITLE D_DOT var_ASIGNACION:e1 contMO_F2:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setTitulo(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       NAME D_DOT ASIGNACION:e1 contMO_F3:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setNombre(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       THEME D_DOT ASIGNACION:e1 contMO_F4:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setTema(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;
//-----------------------------------------------------
contMO_F1       ::=     COM TITLE D_DOT var_ASIGNACION:e1 contMO_F5:e2
                {:
                        if(e2!=null && e1!=null){
                                ((formulario)e2).setTitulo(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM NAME D_DOT ASIGNACION:e1 contMO_F6:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setNombre(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM THEME D_DOT ASIGNACION:e1 contMO_F7:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setTema(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;

contMO_F2       ::=     COM ID D_DOT ASIG_ID:e1 contMO_F5:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setId(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM NAME D_DOT ASIGNACION:e1 contMO_F8:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setNombre(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM THEME D_DOT ASIGNACION:e1 contMO_F9:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setTema(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;

contMO_F3       ::=     COM ID D_DOT ASIG_ID:e1 contMO_F6:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setId(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM TITLE D_DOT var_ASIGNACION:e1 contMO_F8:e2
                {:
                        if(e2!=null && e1!=null){
                                ((formulario)e2).setTitulo(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM THEME D_DOT ASIGNACION:e1 contMO_F10:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setTema(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;

contMO_F4       ::=     COM ID D_DOT ASIG_ID:e1 contMO_F7:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setId(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM TITLE D_DOT var_ASIGNACION:e1 contMO_F9:e2
                {:
                        if(e1!=null && e2!=null){
                                ((formulario)e2).setTitulo(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM NAME D_DOT ASIGNACION:e1 contMO_F10:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setNombre(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;
//-----------------------------------------------------
contMO_F5       ::=     COM NAME D_DOT ASIGNACION:e1 contMO_F11:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setNombre(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM THEME D_DOT ASIGNACION:e1 contMO_F12:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setTema(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |
                {:
                        RESULT = new formulario("","","","","","");
                :}
                |       error
                ;
contMO_F6       ::=     COM TITLE D_DOT var_ASIGNACION:e1 contMO_F11:e2
                {:
                        if(e1!=null && e2!=null){
                                ((formulario)e2).setTitulo(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM THEME D_DOT ASIGNACION:e1 contMO_F13:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setTema(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |
                {:
                        RESULT = new formulario("","","","","","");
                :}
                |       error
                ;
contMO_F7       ::=     COM TITLE D_DOT var_ASIGNACION:e1 contMO_F12:e2
                {:
                        if(e1!=null && e2!=null){
                                ((formulario)e2).setTitulo(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM NAME D_DOT ASIGNACION:e1 contMO_F13:e2\
                {:
                        if(e2!=null){
                                ((formulario)e2).setNombre(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |
                {:
                        RESULT = new formulario("","","","","","");
                :}
                |       error
                ;
contMO_F8       ::=     COM ID D_DOT ASIG_ID:e1 contMO_F11:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setId(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM THEME D_DOT ASIGNACION:e1 contMO_F14:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setTema(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;
contMO_F9       ::=     COM ID D_DOT ASIG_ID:e1 contMO_F12:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setId(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM NAME D_DOT ASIGNACION:e1 contMO_F14:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setNombre(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;
contMO_F10      ::=     COM ID D_DOT ASIG_ID:e1 contMO_F13:e2
                {:
                        if(e2!=null){
                                ((formulario)e2).setId(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       COM TITLE D_DOT var_ASIGNACION:e1 contMO_F14:e2
                {:
                        if(e1!=null && e2!=null){
                                ((formulario)e2).setTitulo(((token)e1).getLexeme());
                                RESULT = e2;
                        }
                :}
                |       error
                ;
//-------------------------------------------------------
contMO_F11      ::=     COM THEME D_DOT ASIGNACION:e1
                {:
                        RESULT = new formulario("","","",((token)e1).getLexeme(),"","");
                :}
                |
                {:
                        RESULT = new formulario("","","","","","");
                :}
                |       error
                ;

contMO_F12      ::=     COM NAME D_DOT ASIGNACION:e1
                {:
                        RESULT = new formulario("","",((token)e1).getLexeme(),"","","");
                :}
                |
                {:
                        RESULT = new formulario("","","","","","");
                :}
                |       error
                ;

contMO_F13      ::=     COM TITLE D_DOT var_ASIGNACION:e1
                {:
                        if(e1!=null){
                                RESULT = new formulario("",((token)e1).getLexeme(),"","","","");
                        }
                :}
                |
                {:
                        RESULT = new formulario("","","","","","");
                :}
                |       error
                ;

contMO_F14      ::=     COM ID D_DOT ASIG_ID:e1
                {:
                        RESULT = new formulario(((token)e1).getLexeme(),"","","","","");
                :}
                |       error
                ;
//PRODUCCIONES PARA ELIMINAR COMPONENTE

paramsDEL_C     ::=     L_A contDEL_C:e1 L_C paramsDEL_C2:e2
                {:
                        if(e1!=null){
                                ((componente)e1).setAccion("ELIMINAR_COMPONENTE");
                                //instrucciones.add(e1);
                                //delComp.add((componente)e1);
                                if(e2!=null){
                                        ((List<Object>)e2).add(e1);
                                        RESULT = e2;
                                }
                        }
                :}
                |       error
                ;
paramsDEL_C2    ::=     COM paramsDEL_C:e1
                {:
                        RESULT =e1;
                :}
                |
                {:
                        RESULT = new ArrayList<Object>();
                :}
                |       error
                ;
//--------------------------------------------------
contDEL_C       ::=     ID D_DOT ASIG_ID:e1 contDEL_C1:e2
                {:
                        if(e2!=null){
                                ((componente)e2).setId(((token)e1).getLexeme());
                                RESULT =e2;
                        }
                :}
                |       FORM D_DOT ASIG_ID:e1 contDEL_C2:e2
                {:
                        if(e2!=null){
                                ((componente)e2).setForm(((token)e1).getLexeme());
                                RESULT =e2;
                        }
                :}
                |       error
                ;
contDEL_C1      ::=     COM FORM D_DOT ASIG_ID:e1
                {:
                        componente comp = new componente();
                        comp.setForm(((token)e1).getLexeme());
                        RESULT=comp;
                :}
                |       error
                ;
contDEL_C2      ::=     COM ID D_DOT ASIG_ID:e1
                {:
                        componente comp = new componente();
                        comp.setId(((token)e1).getLexeme());
                        RESULT=comp;
                :}
                |       error
                ;
//PRODUCCIONES PARA AGREGAR UN COMPONENTE A UN FORMULARIO

paramsADD_C     ::=     L_A:e2 contADD_C:e1 L_C paramsADD_C2:e3
                {:
                        if(e1!=null){
                                String tmp = ((componente)e1).validarComponete();
                                if(tmp.isEmpty()){
                                        ((componente)e1).setAccion("AGREGAR_COMPONENTE");
                                        //instrucciones.add(e1);
                                        //addComp.add(((componente)e1));
                                        if(e3!=null){
                                                ((List<Object>)e3).add(e1);
                                                RESULT = e3;
                                        }
                                }else{
                                        errorVerificacion(tmp,e2);
                                }
                                
                        }
                :}
                |       error
                ;

paramsADD_C2    ::=     COM paramsADD_C:e1
                {:
                        RESULT =e1;
                :}
                |
                {:
                        RESULT = new ArrayList<Object>();
                :}
                |       error
                ;
//--------------------------------------------------------
contADD_C       ::=     ID:p D_DOT ASIG_ID:e1 contADD_C1:e2
                {:      
                        if(e2!=null){
                                //System.out.println("Argrego info y retorno id");
                                if(((componente)e2).getId() == null)
                                {
                                        ((componente)e2).setId(((token)e1).getLexeme());
                                        //System.out.println(((componente)e2).toString());
                                        RESULT = e2;
                                }else{
                                        errorParametroDuplicado(p);
                                }
                                
                        }
                :}
                |       NAME_CAMP:p D_DOT ASIGNACION:e1 contADD_C1:e2
                {:
                        if(e2!=null){
                                //System.out.println("Argrego info y retorno nombre");
                                if(((componente)e2).getNombre() == null){
                                        ((componente)e2).setNombre(((token)e1).getLexeme());
                                        //System.out.println(((componente)e2).toString());
                                        RESULT = e2;
                                }else{
                                        errorParametroDuplicado(p);
                                }
                        }
                :}
                |       FORM:p D_DOT ASIG_ID:e1 contADD_C1:e2
                {:
                        if(e2!=null){
                                //System.out.println("Argrego info y retorno formulario");
                                if(((componente)e2).getForm() == null){
                                        ((componente)e2).setForm(((token)e1).getLexeme());
                                        //System.out.println(((componente)e2).toString());
                                        RESULT = e2;
                                }else{
                                        errorParametroDuplicado(p);
                                }
                        }
                :}
                |       CLASS:p D_DOT contADD_C_2:e1 contADD_C1:e2
                {:
                        if(e2!=null && e1!= null){
                                //System.out.println("Argrego info y retorno clase");
                                if(((componente)e2).getClase() == null){
                                        ((componente)e2).setClase(((token)e1).getLexeme());
                                        //System.out.println(((componente)e2).toString());
                                        RESULT = e2;
                                }else{
                                        errorParametroDuplicado(p);
                                }
                        }
                :}
                |       TEXT_VIEW:p D_DOT var_ASIGNACION:e1 contADD_C1:e2
                {:
                        if(e2!=null && e1!= null){
                                //System.out.println("Argrego info y retorno texto visible");
                                if(((componente)e2).getTexto() == null){
                                        ((componente)e2).setTexto(((token)e1).getLexeme());
                                        //System.out.println(((componente)e2).toString());
                                        RESULT = e2;
                                }else{
                                        errorParametroDuplicado(p);
                                }
                        }
                :}
                |       ALI:p D_DOT contADD_C_1:e1 contADD_C1:e2\
                {:
                        if(e2!=null && e1!=null){
                                //System.out.println("Argrego info y retorno alineacion");
                                if(((componente)e2).getAli() == null){
                                        ((componente)e2).setAli(((token)e1).getLexeme());
                                        //System.out.println(((componente)e2).toString());
                                        RESULT = e2;
                                }else{
                                        errorParametroDuplicado(p);
                                }
                        }
                :}
                |       REQUE:p D_DOT contADD_C2:e1 contADD_C1:e2
                {:
                        if(e2!=null && e1!=null){
                                //System.out.println("Argrego info y retorno requerido");
                                if(((componente)e2).getRequerido() == null){
                                        ((componente)e2).setRequerido(((token)e1).getLexeme());
                                        //System.out.println(((componente)e2).toString());
                                        RESULT = e2;
                                }else{
                                        errorParametroDuplicado(p);
                                }
                        }
                :}
                |       OPTION:p D_DOT var_ASIGNACION:e1 contADD_C1:e2
                {:
                        if(e2!=null && e1!=null){
                                //System.out.println("Argrego info y retorno opcion");
                                if(((componente)e2).getOpciones() == null){
                                        ((componente)e2).setOpciones(((token)e1).getLexeme());
                                        //System.out.println(((componente)e2).toString());
                                        RESULT = e2;
                                }else{
                                        errorParametroDuplicado(p);
                                }
                        }
                :}
                |       URL:p D_DOT var_ASIGNACION:e1 contADD_C1:e2
                {:
                        if(e2!=null && e1!=null){
                                //System.out.println("Argrego info y retorno url");
                                if(((componente)e2).getUrl() == null){
                                        ((componente)e2).setUrl(((token)e1).getLexeme());
                                        //System.out.println(((componente)e2).toString());
                                        RESULT = e2;
                                }else{
                                        errorParametroDuplicado(p);
                                }
                        }
                :}
                |       COLM:p D_DOT ASIGNACION_NUM:e1 contADD_C1:e2
                {:
                        if(e2!=null){
                                //System.out.println("Argrego info y retorno columnas");
                                if(((componente)e2).getColumnas() == null){
                                        ((componente)e2).setColumnas(((token)e1).getLexeme());
                                        //System.out.println(((componente)e2).toString());
                                        RESULT = e2;
                                }else{
                                        errorParametroDuplicado(p);
                                }
                        }
                :}
                |       FILAS:p D_DOT ASIGNACION_NUM:e1 contADD_C1:e2
                {:
                        if(e2!=null){
                                //System.out.println("Argrego info y retorno filas");
                                if(((componente)e2).getFilas() == null){
                                        ((componente)e2).setFilas(((token)e1).getLexeme());
                                        //System.out.println(((componente)e2).toString());
                                        RESULT = e2;
                                }else{
                                        errorParametroDuplicado(p);
                                }
                        }
                :}
                ;

contADD_C1      ::=     COM contADD_C:e1
                {:
                        if(e1!=null){
                                //System.out.println("Retorno componente");
                                //System.out.println(((componente)e1).toString());
                                RESULT = e1;
                        }
                :}
                |
                {:
                        //System.out.println("Genero componente");
                        RESULT = new componente();
                :}
                |       error
                ;

contADD_C_1     ::=     CENT:e1
                {:
                        RESULT = e1;
                :}
                |       IZQ:e1
                {:
                        RESULT = e1;
                :}
                |       DER:e1
                {:
                        RESULT = e1;
                :}
                |       JUST:e1
                {:
                        RESULT = e1;
                :}
                |       error
                ;

contADD_C_2     ::=     CAMP_TEXT:e1
                {:
                        RESULT = e1;
                :}
                |       TEXT_AREA:e1
                {:
                        RESULT = e1;
                :}
                |       CHECK:e1
                {:
                        RESULT = e1;
                :}
                |       RADIO:e1
                {:
                        RESULT = e1;
                :}
                |       FILE:e1
                {:
                        RESULT = e1;
                :}
                |       IMG:e1
                {:
                        RESULT = e1;
                :}
                |       COMBO:e1
                {:
                        RESULT = e1;
                :}
                |       BOTON:e1
                {:
                        RESULT = e1;
                :}
                |       error
                ;

contADD_C2      ::=     YES:e1
                {:
                        RESULT = e1;
                :}
                |       NOT:e1
                {:
                        RESULT = e1;
                :}
                |       error
                ;

//PRODUCCIONES PARA MODIFICAR COMPONENTE
paramsMO_C      ::=     L_A contMO_C:e1 L_C paramsMO_C2:e2
                {:
                        if(e1!=null){
                                ((componente)e1).setAccion("MODIFICAR_COMPONENTE");
                                //instrucciones.add(e1);
                                //modComp.add((componente)e1);
                                if(e2!=null){
                                        ((List<Object>)e2).add(e1);
                                        RESULT = e2;
                                }
                        }
                :}
                |       error
                ;
paramsMO_C2     ::=     COM paramsMO_C:e1
                {:
                        RESULT =e1;
                :}
                |       
                {:
                        RESULT = new ArrayList<Object>();
                :}
                |       error
                ;

contMO_C       ::=      ID:p D_DOT ASIG_ID:e1 contMO_C1:e2
                {:      
                        if(e2!=null){
                                //System.out.println("Argrego info y retorno id");
                                if(((componente)e2).getId() == null)
                                {
                                        ((componente)e2).setId(((token)e1).getLexeme());
                                        //System.out.println(((componente)e2).toString());
                                        RESULT = e2;
                                }else{
                                        errorParametroDuplicado(p);
                                }
                                
                        }
                :}
                |       NAME_CAMP:p D_DOT ASIGNACION:e1 contMO_C1:e2
                {:
                        if(e2!=null){
                                //System.out.println("Argrego info y retorno nombre");
                                if(((componente)e2).getNombre() == null){
                                        ((componente)e2).setNombre(((token)e1).getLexeme());
                                        //System.out.println(((componente)e2).toString());
                                        RESULT = e2;
                                }else{
                                        errorParametroDuplicado(p);
                                }
                        }
                :}
                |       FORM:p D_DOT ASIG_ID:e1 contMO_C1:e2
                {:
                        if(e2!=null){
                                //System.out.println("Argrego info y retorno formulario");
                                if(((componente)e2).getForm() == null){
                                        ((componente)e2).setForm(((token)e1).getLexeme());
                                        //System.out.println(((componente)e2).toString());
                                        RESULT = e2;
                                }else{
                                        errorParametroDuplicado(p);
                                }
                        }
                :}
                |       CLASS:p D_DOT contMO_C_2:e1 contMO_C1:e2
                {:
                        if(e2!=null && e1!= null){
                                //System.out.println("Argrego info y retorno clase");
                                if(((componente)e2).getClase() == null){
                                        ((componente)e2).setClase(((token)e1).getLexeme());
                                        //System.out.println(((componente)e2).toString());
                                        RESULT = e2;
                                }else{
                                        errorParametroDuplicado(p);
                                }
                        }
                :}
                |       IND:p D_DOT ASIGNACION_NUM:e1 contMO_C1:e2
                {:
                        if(e2!=null){
                                //System.out.println("Argrego info y retorno formulario");
                                if(((componente)e2).getIndice() == null){
                                        ((componente)e2).setIndice(((token)e1).getLexeme());
                                        //System.out.println(((componente)e2).toString());
                                        RESULT = e2;
                                }else{
                                        errorParametroDuplicado(p);
                                }
                        }
                :}
                |       TEXT_VIEW:p D_DOT var_ASIGNACION:e1 contMO_C1:e2
                {:
                        if(e2!=null && e1!= null){
                                //System.out.println("Argrego info y retorno texto visible");
                                if(((componente)e2).getTexto() == null){
                                        ((componente)e2).setTexto(((token)e1).getLexeme());
                                        //System.out.println(((componente)e2).toString());
                                        RESULT = e2;
                                }else{
                                        errorParametroDuplicado(p);
                                }
                        }
                :}
                |       ALI:p D_DOT contMO_C_1:e1 contMO_C1:e2
                {:
                        if(e2!=null && e1!=null){
                                //System.out.println("Argrego info y retorno alineacion");
                                if(((componente)e2).getAli() == null){
                                        ((componente)e2).setAli(((token)e1).getLexeme());
                                        //System.out.println(((componente)e2).toString());
                                        RESULT = e2;
                                }else{
                                        errorParametroDuplicado(p);
                                }
                        }
                :}
                |       REQUE:p D_DOT contMO_C2:e1 contMO_C1:e2
                {:
                        if(e2!=null && e1!=null){
                                //System.out.println("Argrego info y retorno requerido");
                                if(((componente)e2).getRequerido() == null){
                                        ((componente)e2).setRequerido(((token)e1).getLexeme());
                                        //System.out.println(((componente)e2).toString());
                                        RESULT = e2;
                                }else{
                                        errorParametroDuplicado(p);
                                }
                        }
                :}
                |       OPTION:p D_DOT var_ASIGNACION:e1 contMO_C1:e2
                {:
                        if(e2!=null && e1!=null){
                                //System.out.println("Argrego info y retorno opcion");
                                if(((componente)e2).getOpciones() == null){
                                        ((componente)e2).setOpciones(((token)e1).getLexeme());
                                        //System.out.println(((componente)e2).toString());
                                        RESULT = e2;
                                }else{
                                        errorParametroDuplicado(p);
                                }
                        }
                :}
                |       URL:p D_DOT var_ASIGNACION:e1 contMO_C1:e2
                {:
                        if(e2!=null && e1!=null){
                                //System.out.println("Argrego info y retorno url");
                                if(((componente)e2).getUrl() == null){
                                        ((componente)e2).setUrl(((token)e1).getLexeme());
                                        //System.out.println(((componente)e2).toString());
                                        RESULT = e2;
                                }else{
                                        errorParametroDuplicado(p);
                                }
                        }
                :}
                |       COLM:p D_DOT ASIGNACION_NUM:e1 contMO_C1:e2
                {:
                        if(e2!=null){
                                //System.out.println("Argrego info y retorno columnas");
                                if(((componente)e2).getColumnas() == null){
                                        ((componente)e2).setColumnas(((token)e1).getLexeme());
                                        //System.out.println(((componente)e2).toString());
                                        RESULT = e2;
                                }else{
                                        errorParametroDuplicado(p);
                                }
                        }
                :}
                |       FILAS:p D_DOT ASIGNACION_NUM:e1 contMO_C1:e2
                {:
                        if(e2!=null){
                                //System.out.println("Argrego info y retorno filas");
                                if(((componente)e2).getFilas() == null){
                                        ((componente)e2).setFilas(((token)e1).getLexeme());
                                        //System.out.println(((componente)e2).toString());
                                        RESULT = e2;
                                }else{
                                        errorParametroDuplicado(p);
                                }
                        }
                :}
                |       error
                ;

contMO_C1      ::=      COM contMO_C:e1
                {:
                        if(e1!=null){
                                RESULT=e1;
                        }
                :}
                |
                {:
                        RESULT = new componente();
                :}
                |       error
                ;

contMO_C_1     ::=     CENT:e1
                {:
                        RESULT = e1;
                :}
                |       IZQ:e1
                {:
                        RESULT = e1;
                :}
                |       DER:e1
                {:
                        RESULT = e1;
                :}
                |       JUST:e1
                {:
                        RESULT = e1;
                :}
                |       error
                ;

contMO_C_2     ::=     CAMP_TEXT:e1
                {:
                        RESULT = e1;
                :}
                |       TEXT_AREA:e1
                {:
                        RESULT = e1;
                :}
                |       CHECK:e1
                {:
                        RESULT = e1;
                :}
                |       RADIO:e1
                {:
                        RESULT = e1;
                :}
                |       FILE:e1
                {:
                        RESULT = e1;
                :}
                |       IMG:e1
                {:
                        RESULT = e1;
                :}
                |       COMBO:e1
                {:
                        RESULT = e1;
                :}
                |       BOTON:e1
                {:
                        RESULT = e1;
                :}
                |       error
                ;


contMO_C2       ::=     YES:e1
                {:
                        RESULT = e1;
                :}
                |       NOT:e1
                {:
                        RESULT = e1;
                :}
                |       error
                ;
//PRODUCCIONES PARA LA RECEPCION DE ERRORES LEXICOS
paramsERL       ::=     L_A contMJ:e1 L_C paramsERL2
                {:
                        if(e1!=null){
                                errLex.add(((mensaje)e1));
                        }        
                :}
                |       error
                ;

paramsERL2      ::=     COM paramsERL
                |
                |       error
                ;

contMJ ::=     MJS D_DOT var_ASIGNACION:e1
        {:
                if(e1!=null){
                        RESULT = new mensaje(((token)e1).getLexeme());
                }
        :}
        |       error
        ;
//PRODUCCIONES PARA LA RECEPCION DE ERRORES SINTACTICOS
paramsERS       ::=     L_A contMJ:e1 L_C paramsERS2
                {:
                        if(e1!=null){
                                errSin.add(((mensaje)e1));
                        }
                :}
                |       error
                ;
paramsERS2      ::=     COM paramsERS
                |
                |       error
                ;
//PROCUCCIONES PARA LA RECEPCION DE MENSAJES AL USUARIO
paramsMJS       ::=     L_A contMJ:e1 L_C paramsMJS2
                {:
                        if(e1!=null){
                                msjUser.add(((mensaje)e1));
                        }
                :}
                |       error
                ;
paramsMJS2      ::=     COM paramsMJS
                |
                |       error
                ;