
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.carlos.app_cliente_proyecto1.Parser;

import com.carlos.app_cliente_proyecto1.Lexer.lexerIndigo;
import java.util.ArrayList;
import java.util.List;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parserIndigo extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return parserIndigoSym.class;
}

  /** Default constructor. */
  @Deprecated
  public parserIndigo() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parserIndigo(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parserIndigo(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\005\000\002\002\003\000\002\002\004\000\002\002" +
    "\003\000\002\002\003\000\002\002\002" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\006\000\012\002\ufffd\003\005\004\006\005\004\001" +
    "\002\000\004\002\uffff\001\002\000\004\002\ufffe\001\002" +
    "\000\004\002\001\001\002\000\004\002\010\001\002\000" +
    "\004\002\000\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\006\000\004\002\006\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parserIndigo$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parserIndigo$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parserIndigo$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



        private List<String> errorsList = new ArrayList();

        public parserIndigo(lexerIndigo lex){
                super(lex);
        }

        public void report_error(String message, Object info){
                System.out.println("reporterror");
        }
        public void report_fatal_error(String message, Object info){
                System.out.println("reportfatal");
        }
        /*
        public void syntax_error(Symbol cur_token){
                
        }*/
        protected int error_sync_size() {
		return 1;
	}
        public List<String> getErrorsList(){
	        return errorsList
	        ;
	}



/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parserIndigo$actions {
  private final parserIndigo parser;

  /** Constructor */
  CUP$parserIndigo$actions(parserIndigo parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parserIndigo$do_action_part00000000(
    int                        CUP$parserIndigo$act_num,
    java_cup.runtime.lr_parser CUP$parserIndigo$parser,
    java.util.Stack            CUP$parserIndigo$stack,
    int                        CUP$parserIndigo$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parserIndigo$result;

      /* select the action based on the action number */
      switch (CUP$parserIndigo$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // exp ::= ME_Q 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("exp",0, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= exp EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-1)).value;
		RESULT = start_val;
              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-1)), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parserIndigo$parser.done_parsing();
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // exp ::= MA_Q 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("exp",0, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // exp ::= error 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("exp",0, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // exp ::= 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("exp",0, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parserIndigo$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parserIndigo$do_action(
    int                        CUP$parserIndigo$act_num,
    java_cup.runtime.lr_parser CUP$parserIndigo$parser,
    java.util.Stack            CUP$parserIndigo$stack,
    int                        CUP$parserIndigo$top)
    throws java.lang.Exception
    {
              return CUP$parserIndigo$do_action_part00000000(
                               CUP$parserIndigo$act_num,
                               CUP$parserIndigo$parser,
                               CUP$parserIndigo$stack,
                               CUP$parserIndigo$top);
    }
}

}
