
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.carlos.app_cliente_proyecto1.Parser;

/** CUP generated class containing symbol constants. */
public class parserIndigoSym {
  /* terminals */
  public static final int ME_Q = 2;
  public static final int THEME = 41;
  public static final int SCR = 77;
  public static final int ERS = 75;
  public static final int SS = 5;
  public static final int SR = 72;
  public static final int ERL = 74;
  public static final int C_C = 12;
  public static final int MA_Q = 3;
  public static final int MJS = 71;
  public static final int C_A = 11;
  public static final int NAME = 40;
  public static final int PASS = 17;
  public static final int FS = 6;
  public static final int FR = 73;
  public static final int ASIG_ID = 69;
  public static final int DES = 70;
  public static final int DER = 65;
  public static final int ALI = 48;
  public static final int D_DOT = 10;
  public static final int NOT = 67;
  public static final int ASIGNACION_ESP = 20;
  public static final int CR_U = 15;
  public static final int FILAS = 51;
  public static final int JUST = 66;
  public static final int CLASS = 45;
  public static final int TEXT_VIEW = 47;
  public static final int PARAMS_COMP = 23;
  public static final int CONSULT = 80;
  public static final int CONSULT_DATA = 79;
  public static final int FECHA = 18;
  public static final int SSS = 7;
  public static final int CENT = 63;
  public static final int PASS_NEW = 36;
  public static final int FCR = 78;
  public static final int USER_ANT = 34;
  public static final int ADM = 4;
  public static final int NUM_CONSULT = 81;
  public static final int COLM = 52;
  public static final int USER_NEW = 35;
  public static final int YES = 68;
  public static final int NEW_F = 27;
  public static final int URL = 53;
  public static final int ADD_C = 30;
  public static final int FORM = 44;
  public static final int EOF = 0;
  public static final int LOG_U = 26;
  public static final int REQUE = 49;
  public static final int COM = 9;
  public static final int MO_U = 24;
  public static final int IZQ = 64;
  public static final int TABLA_CON = 82;
  public static final int IND = 46;
  public static final int TEXT_AREA = 56;
  public static final int ASIGNACION_NUM = 21;
  public static final int PARAMS_FORM = 54;
  public static final int DEL_U = 25;
  public static final int TITLE = 39;
  public static final int DATE = 33;
  public static final int MO_F = 29;
  public static final int error = 1;
  public static final int BOTON = 62;
  public static final int MO_C = 32;
  public static final int MJSU = 76;
  public static final int ID = 38;
  public static final int CREDEN_USER = 22;
  public static final int DEL_F = 28;
  public static final int CHECK = 57;
  public static final int DEL_C = 31;
  public static final int IMG = 60;
  public static final int FILE = 59;
  public static final int L_C = 14;
  public static final int RADIO = 58;
  public static final int L_A = 13;
  public static final int USER_CRE = 42;
  public static final int NAME_CAMP = 43;
  public static final int CAMP_TEXT = 55;
  public static final int ASIGNACION = 19;
  public static final int OPTION = 50;
  public static final int FSS = 8;
  public static final int COMBO = 61;
  public static final int FECHA_MOD = 37;
  public static final int USER = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ME_Q",
  "MA_Q",
  "ADM",
  "SS",
  "FS",
  "SSS",
  "FSS",
  "COM",
  "D_DOT",
  "C_A",
  "C_C",
  "L_A",
  "L_C",
  "CR_U",
  "USER",
  "PASS",
  "FECHA",
  "ASIGNACION",
  "ASIGNACION_ESP",
  "ASIGNACION_NUM",
  "CREDEN_USER",
  "PARAMS_COMP",
  "MO_U",
  "DEL_U",
  "LOG_U",
  "NEW_F",
  "DEL_F",
  "MO_F",
  "ADD_C",
  "DEL_C",
  "MO_C",
  "DATE",
  "USER_ANT",
  "USER_NEW",
  "PASS_NEW",
  "FECHA_MOD",
  "ID",
  "TITLE",
  "NAME",
  "THEME",
  "USER_CRE",
  "NAME_CAMP",
  "FORM",
  "CLASS",
  "IND",
  "TEXT_VIEW",
  "ALI",
  "REQUE",
  "OPTION",
  "FILAS",
  "COLM",
  "URL",
  "PARAMS_FORM",
  "CAMP_TEXT",
  "TEXT_AREA",
  "CHECK",
  "RADIO",
  "FILE",
  "IMG",
  "COMBO",
  "BOTON",
  "CENT",
  "IZQ",
  "DER",
  "JUST",
  "NOT",
  "YES",
  "ASIG_ID",
  "DES",
  "MJS",
  "SR",
  "FR",
  "ERL",
  "ERS",
  "MJSU",
  "SCR",
  "FCR",
  "CONSULT_DATA",
  "CONSULT",
  "NUM_CONSULT",
  "TABLA_CON"
  };
}

