
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.carlos.web_proyecto1.Parser;

/** CUP generated class containing symbol constants. */
public class parserSQFORMSym {
  /* terminals */
  public static final int C_A = 14;
  public static final int WHERE = 8;
  public static final int MA_Q = 12;
  public static final int AND = 2;
  public static final int ME_EQ = 18;
  public static final int SELECT = 5;
  public static final int OR = 3;
  public static final int VALUE = 20;
  public static final int NOT = 4;
  public static final int ME_Q = 11;
  public static final int FORM = 7;
  public static final int NUM = 19;
  public static final int MA_EQ = 17;
  public static final int COMA = 9;
  public static final int EOF = 0;
  public static final int DIR = 10;
  public static final int error = 1;
  public static final int EQ = 16;
  public static final int ME_Q_MA_Q = 13;
  public static final int PARAM = 21;
  public static final int TO = 6;
  public static final int C_C = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "AND",
  "OR",
  "NOT",
  "SELECT",
  "TO",
  "FORM",
  "WHERE",
  "COMA",
  "DIR",
  "ME_Q",
  "MA_Q",
  "ME_Q_MA_Q",
  "C_A",
  "C_C",
  "EQ",
  "MA_EQ",
  "ME_EQ",
  "NUM",
  "VALUE",
  "PARAM"
  };
}

