
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.carlos.web_proyecto1.Parser;

import com.carlos.web_proyecto1.EDD.*;
import com.carlos.web_proyecto1.Lexer.lexerSQFORM;
import com.carlos.web_proyecto1.Tokens.token;
import java.util.ArrayList;
import java.util.List;
import java_cup.runtime.Symbol;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parserSQFORM extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return parserSQFORMSym.class;
}

  /** Default constructor. */
  @Deprecated
  public parserSQFORM() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parserSQFORM(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parserSQFORM(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\013\000\002\002\004\000\002\002\007\000\002\002" +
    "\003\000\002\003\007\000\002\003\007\000\002\003\003" +
    "\000\002\004\004\000\002\004\003\000\002\006\004\000" +
    "\002\006\002\000\002\006\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\032\000\006\003\004\007\006\001\002\000\004\002" +
    "\uffff\001\002\000\004\002\034\001\002\000\004\010\007" +
    "\001\002\000\004\011\010\001\002\000\004\014\011\001" +
    "\002\000\010\003\014\027\015\030\012\001\002\000\004" +
    "\020\030\001\002\000\004\002\000\001\002\000\004\002" +
    "\ufffc\001\002\000\004\020\016\001\002\000\006\003\020" +
    "\027\021\001\002\000\004\021\026\001\002\000\004\021" +
    "\ufffa\001\002\000\010\003\023\013\022\021\ufff8\001\002" +
    "\000\006\003\020\027\021\001\002\000\004\021\ufff7\001" +
    "\002\000\004\021\ufffb\001\002\000\004\021\ufff9\001\002" +
    "\000\002\001\002\000\004\002\ufffd\001\002\000\006\003" +
    "\020\027\021\001\002\000\004\021\032\001\002\000\002" +
    "\001\002\000\004\002\ufffe\001\002\000\004\002\001\001" +
    "\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\032\000\004\002\004\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\003\012\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\004\016\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\006\023\001\001\000\004\004\024\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\005" +
    "\026\001\001\000\002\001\001\000\004\004\030\001\001" +
    "\000\002\001\001\000\004\005\032\001\001\000\002\001" +
    "\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parserSQFORM$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parserSQFORM$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parserSQFORM$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




    private List<String> errorsList = new ArrayList();

    public parserSQFORM(lexerSQFORM lex){
        super(lex);
    }

    public void report_error(String message, Object info){
        Symbol symbol = cur_token;
        token tok = (token)symbol.value;
        if (tok != null) {
            System.out.println("Parametro inesperado: |" + ((tok.getLexeme().equals("\"")) ? "comilla" : tok.getLexeme()) + "| Linea: " + tok.getLine() + ", Columna: " + tok.getColumn());
            errorsList.add("Parametro inesperado: |" + ((tok.getLexeme().equals("\"")) ? "comilla" : tok.getLexeme()) + "| Linea: " + tok.getLine() + ", Columna: " + tok.getColumn());
        }
    }

    public void report_fatal_error(String message, Object info){
        System.out.println(info.toString());
        System.out.println("reportfatal");
    }
        
    public void errorVerificacion(String mensage,Object info){
        token tok = (token)info;
        System.out.println(mensage+"Componente ubicado en Linea: "+tok.getLine()+", Columna: "+tok.getColumn());
        errorsList.add(mensage+"Componente ubicado en Linea: "+tok.getLine()+", Columna: "+tok.getColumn());
    }

    public void errorParametroDuplicado(Object simbolo){
        token tok = (token)simbolo;
        System.out.println("El parametro ubicado en Linea: "+tok.getLine()+", Columna: "+tok.getColumn()+" ya se habia definido con anterioridad");
        errorsList.add("El parametro ubicado en Linea: "+tok.getLine()+", Columna: "+tok.getColumn()+" ya se habia definido con anterioridad");
    }

    protected int error_sync_size() {
		return 1;
	}
    public List<String> getErrorsList(){
	    return errorsList;
	}



/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parserSQFORM$actions {
  private final parserSQFORM parser;

  /** Constructor */
  CUP$parserSQFORM$actions(parserSQFORM parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parserSQFORM$do_action_part00000000(
    int                        CUP$parserSQFORM$act_num,
    java_cup.runtime.lr_parser CUP$parserSQFORM$parser,
    java.util.Stack            CUP$parserSQFORM$stack,
    int                        CUP$parserSQFORM$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parserSQFORM$result;

      /* select the action based on the action number */
      switch (CUP$parserSQFORM$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= inicio EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.elementAt(CUP$parserSQFORM$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.elementAt(CUP$parserSQFORM$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parserSQFORM$stack.elementAt(CUP$parserSQFORM$top-1)).value;
		RESULT = start_val;
              CUP$parserSQFORM$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.elementAt(CUP$parserSQFORM$top-1)), ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parserSQFORM$parser.done_parsing();
          return CUP$parserSQFORM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // inicio ::= SELECT TO FORM DIR formulario 
            {
              Object RESULT =null;

              CUP$parserSQFORM$result = parser.getSymbolFactory().newSymbol("inicio",0, ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.elementAt(CUP$parserSQFORM$top-4)), ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), RESULT);
            }
          return CUP$parserSQFORM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // inicio ::= error 
            {
              Object RESULT =null;

              CUP$parserSQFORM$result = parser.getSymbolFactory().newSymbol("inicio",0, ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), RESULT);
            }
          return CUP$parserSQFORM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // formulario ::= ID C_A camposProyectar C_C condicional 
            {
              Object RESULT =null;

              CUP$parserSQFORM$result = parser.getSymbolFactory().newSymbol("formulario",1, ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.elementAt(CUP$parserSQFORM$top-4)), ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), RESULT);
            }
          return CUP$parserSQFORM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // formulario ::= PARAM C_A camposProyectar C_C condicional 
            {
              Object RESULT =null;

              CUP$parserSQFORM$result = parser.getSymbolFactory().newSymbol("formulario",1, ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.elementAt(CUP$parserSQFORM$top-4)), ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), RESULT);
            }
          return CUP$parserSQFORM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // formulario ::= error 
            {
              Object RESULT =null;

              CUP$parserSQFORM$result = parser.getSymbolFactory().newSymbol("formulario",1, ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), RESULT);
            }
          return CUP$parserSQFORM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // camposProyectar ::= PARAM camposProyectarP 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.elementAt(CUP$parserSQFORM$top-1)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.elementAt(CUP$parserSQFORM$top-1)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parserSQFORM$stack.elementAt(CUP$parserSQFORM$top-1)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$parserSQFORM$stack.peek()).value;
		
                    if(e2!=null){
                        token tok = ((token)e1);
                        
                        if(((Pila)e2).buscarTag(tok.getLexeme())==false){
                            ((Pila)e2).push(tok.getLexeme(),tok.getLexeme());
                        }else{
                            errorParametroDuplicado(e1);
                        }
                    }
                    RESULT = e2;
                
              CUP$parserSQFORM$result = parser.getSymbolFactory().newSymbol("camposProyectar",2, ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.elementAt(CUP$parserSQFORM$top-1)), ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), RESULT);
            }
          return CUP$parserSQFORM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // camposProyectar ::= error 
            {
              Object RESULT =null;

              CUP$parserSQFORM$result = parser.getSymbolFactory().newSymbol("camposProyectar",2, ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), RESULT);
            }
          return CUP$parserSQFORM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // camposProyectarP ::= COMA camposProyectar 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parserSQFORM$stack.peek()).value;
		
                        RESULT = e1;
                    
              CUP$parserSQFORM$result = parser.getSymbolFactory().newSymbol("camposProyectarP",4, ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.elementAt(CUP$parserSQFORM$top-1)), ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), RESULT);
            }
          return CUP$parserSQFORM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // camposProyectarP ::= 
            {
              Object RESULT =null;
		
                        RESULT = new Pila();
                    
              CUP$parserSQFORM$result = parser.getSymbolFactory().newSymbol("camposProyectarP",4, ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), RESULT);
            }
          return CUP$parserSQFORM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // camposProyectarP ::= error 
            {
              Object RESULT =null;

              CUP$parserSQFORM$result = parser.getSymbolFactory().newSymbol("camposProyectarP",4, ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), RESULT);
            }
          return CUP$parserSQFORM$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parserSQFORM$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parserSQFORM$do_action(
    int                        CUP$parserSQFORM$act_num,
    java_cup.runtime.lr_parser CUP$parserSQFORM$parser,
    java.util.Stack            CUP$parserSQFORM$stack,
    int                        CUP$parserSQFORM$top)
    throws java.lang.Exception
    {
              return CUP$parserSQFORM$do_action_part00000000(
                               CUP$parserSQFORM$act_num,
                               CUP$parserSQFORM$parser,
                               CUP$parserSQFORM$stack,
                               CUP$parserSQFORM$top);
    }
}

}
