
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.carlos.web_proyecto1.Parser;

import com.carlos.web_proyecto1.Lexer.lexerSQFORM;
import com.carlos.web_proyecto1.EDD.*;
import com.carlos.web_proyecto1.Tokens.token;
import java.util.ArrayList;
import java.util.List;
import java_cup.runtime.Symbol;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parserSQFORM extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return parserSQFORMSym.class;
}

  /** Default constructor. */
  @Deprecated
  public parserSQFORM() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parserSQFORM(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parserSQFORM(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\041\000\002\002\004\000\002\002\007\000\002\002" +
    "\003\000\002\003\007\000\002\003\007\000\002\003\003" +
    "\000\002\004\004\000\002\004\003\000\002\006\004\000" +
    "\002\006\002\000\002\006\003\000\002\005\006\000\002" +
    "\005\003\000\002\007\006\000\002\007\006\000\002\007" +
    "\003\000\002\010\004\000\002\010\002\000\002\010\003" +
    "\000\002\011\003\000\002\011\003\000\002\011\003\000" +
    "\002\011\003\000\002\013\003\000\002\013\003\000\002" +
    "\013\003\000\002\013\003\000\002\013\003\000\002\013" +
    "\003\000\002\013\003\000\002\012\003\000\002\012\003" +
    "\000\002\012\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\070\000\006\003\004\007\006\001\002\000\004\002" +
    "\uffff\001\002\000\004\002\072\001\002\000\004\010\007" +
    "\001\002\000\004\011\010\001\002\000\004\014\011\001" +
    "\002\000\010\003\014\027\015\030\012\001\002\000\004" +
    "\020\066\001\002\000\004\002\000\001\002\000\004\002" +
    "\ufffc\001\002\000\004\020\016\001\002\000\006\003\020" +
    "\027\021\001\002\000\004\021\026\001\002\000\004\021" +
    "\ufffa\001\002\000\010\003\023\013\022\021\ufff8\001\002" +
    "\000\006\003\020\027\021\001\002\000\004\021\ufff7\001" +
    "\002\000\004\021\ufffb\001\002\000\004\021\ufff9\001\002" +
    "\000\006\003\030\012\027\001\002\000\004\020\032\001" +
    "\002\000\004\002\ufff5\001\002\000\004\002\ufffd\001\002" +
    "\000\010\003\034\027\036\030\033\001\002\000\020\003" +
    "\043\015\045\016\042\017\040\022\041\023\046\024\044" +
    "\001\002\000\004\021\ufff2\001\002\000\004\021\062\001" +
    "\002\000\020\003\043\015\045\016\042\017\040\022\041" +
    "\023\046\024\044\001\002\000\010\003\050\025\047\026" +
    "\052\001\002\000\010\003\uffe5\025\uffe5\026\uffe5\001\002" +
    "\000\010\003\uffe6\025\uffe6\026\uffe6\001\002\000\010\003" +
    "\uffe9\025\uffe9\026\uffe9\001\002\000\010\003\uffe4\025\uffe4" +
    "\026\uffe4\001\002\000\010\003\uffe8\025\uffe8\026\uffe8\001" +
    "\002\000\010\003\uffea\025\uffea\026\uffea\001\002\000\010" +
    "\003\uffe7\025\uffe7\026\uffe7\001\002\000\014\003\uffe3\004" +
    "\uffe3\005\uffe3\006\uffe3\021\uffe3\001\002\000\014\003\uffe1" +
    "\004\uffe1\005\uffe1\006\uffe1\021\uffe1\001\002\000\014\003" +
    "\054\004\055\005\060\006\053\021\ufff0\001\002\000\014" +
    "\003\uffe2\004\uffe2\005\uffe2\006\uffe2\021\uffe2\001\002\000" +
    "\010\003\uffed\027\uffed\030\uffed\001\002\000\012\003\uffeb" +
    "\021\uffef\027\uffeb\030\uffeb\001\002\000\010\003\uffec\027" +
    "\uffec\030\uffec\001\002\000\004\021\ufff3\001\002\000\010" +
    "\003\034\027\036\030\033\001\002\000\010\003\uffee\027" +
    "\uffee\030\uffee\001\002\000\004\021\ufff1\001\002\000\004" +
    "\002\ufff6\001\002\000\010\003\050\025\047\026\052\001" +
    "\002\000\014\003\054\004\055\005\060\006\053\021\ufff0" +
    "\001\002\000\004\021\ufff4\001\002\000\006\003\020\027" +
    "\021\001\002\000\004\021\070\001\002\000\006\003\030" +
    "\012\027\001\002\000\004\002\ufffe\001\002\000\004\002" +
    "\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\070\000\004\002\004\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\003\012\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\004\016\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\006\023\001\001\000\004\004\024\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\005" +
    "\030\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\007\034\001\001\000\004\013\062\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\013\036" +
    "\001\001\000\004\012\050\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\010\055\011\056\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\007\060\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\012\063\001\001\000\006\010\064\011\056\001\001" +
    "\000\002\001\001\000\004\004\066\001\001\000\002\001" +
    "\001\000\004\005\070\001\001\000\002\001\001\000\002" +
    "\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parserSQFORM$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parserSQFORM$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parserSQFORM$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




    private List<String> errorsList = new ArrayList();

    public parserSQFORM(lexerSQFORM lex){
        super(lex);
    }

    public void report_error(String message, Object info){
        Symbol symbol = cur_token;
        token tok = (token)symbol.value;
        if (tok != null) {
            System.out.println("Parametro inesperado: |" + ((tok.getLexeme().equals("\"")) ? "comilla" : tok.getLexeme()) + "| Linea: " + tok.getLine() + ", Columna: " + tok.getColumn());
            errorsList.add("Parametro inesperado: |" + ((tok.getLexeme().equals("\"")) ? "comilla" : tok.getLexeme()) + "| Linea: " + tok.getLine() + ", Columna: " + tok.getColumn());
        }
    }

    public void report_fatal_error(String message, Object info){
        System.out.println(info.toString());
        System.out.println("reportfatal");
    }
        
    public void errorVerificacion(String mensage,Object info){
        token tok = (token)info;
        System.out.println(mensage+"Componente ubicado en Linea: "+tok.getLine()+", Columna: "+tok.getColumn());
        errorsList.add(mensage+"Componente ubicado en Linea: "+tok.getLine()+", Columna: "+tok.getColumn());
    }

    public void errorParametroDuplicado(Object simbolo){
        token tok = (token)simbolo;
        System.out.println("El parametro ubicado en Linea: "+tok.getLine()+", Columna: "+tok.getColumn()+" ya se habia definido con anterioridad");
        errorsList.add("El parametro ubicado en Linea: "+tok.getLine()+", Columna: "+tok.getColumn()+" ya se habia definido con anterioridad");
    }

    protected int error_sync_size() {
		return 1;
	}
    public List<String> getErrorsList(){
	    return errorsList;
	}



/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parserSQFORM$actions {
  private final parserSQFORM parser;

  /** Constructor */
  CUP$parserSQFORM$actions(parserSQFORM parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parserSQFORM$do_action_part00000000(
    int                        CUP$parserSQFORM$act_num,
    java_cup.runtime.lr_parser CUP$parserSQFORM$parser,
    java.util.Stack            CUP$parserSQFORM$stack,
    int                        CUP$parserSQFORM$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parserSQFORM$result;

      /* select the action based on the action number */
      switch (CUP$parserSQFORM$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= inicio EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.elementAt(CUP$parserSQFORM$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.elementAt(CUP$parserSQFORM$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parserSQFORM$stack.elementAt(CUP$parserSQFORM$top-1)).value;
		RESULT = start_val;
              CUP$parserSQFORM$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.elementAt(CUP$parserSQFORM$top-1)), ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parserSQFORM$parser.done_parsing();
          return CUP$parserSQFORM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // inicio ::= SELECT TO FORM DIR formulario 
            {
              Object RESULT =null;

              CUP$parserSQFORM$result = parser.getSymbolFactory().newSymbol("inicio",0, ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.elementAt(CUP$parserSQFORM$top-4)), ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), RESULT);
            }
          return CUP$parserSQFORM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // inicio ::= error 
            {
              Object RESULT =null;

              CUP$parserSQFORM$result = parser.getSymbolFactory().newSymbol("inicio",0, ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), RESULT);
            }
          return CUP$parserSQFORM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // formulario ::= ID C_A camposProyectar C_C condicional 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.elementAt(CUP$parserSQFORM$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.elementAt(CUP$parserSQFORM$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parserSQFORM$stack.elementAt(CUP$parserSQFORM$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$parserSQFORM$stack.peek()).value;
		

            
              CUP$parserSQFORM$result = parser.getSymbolFactory().newSymbol("formulario",1, ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.elementAt(CUP$parserSQFORM$top-4)), ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), RESULT);
            }
          return CUP$parserSQFORM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // formulario ::= PARAM C_A camposProyectar C_C condicional 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.elementAt(CUP$parserSQFORM$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.elementAt(CUP$parserSQFORM$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parserSQFORM$stack.elementAt(CUP$parserSQFORM$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$parserSQFORM$stack.peek()).value;
		

            
              CUP$parserSQFORM$result = parser.getSymbolFactory().newSymbol("formulario",1, ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.elementAt(CUP$parserSQFORM$top-4)), ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), RESULT);
            }
          return CUP$parserSQFORM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // formulario ::= error 
            {
              Object RESULT =null;

              CUP$parserSQFORM$result = parser.getSymbolFactory().newSymbol("formulario",1, ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), RESULT);
            }
          return CUP$parserSQFORM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // camposProyectar ::= PARAM camposProyectarP 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.elementAt(CUP$parserSQFORM$top-1)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.elementAt(CUP$parserSQFORM$top-1)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parserSQFORM$stack.elementAt(CUP$parserSQFORM$top-1)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$parserSQFORM$stack.peek()).value;
		
                    if(e2!=null){
                        token tok = ((token)e1);
                        if(((Pila)e2).buscarTag(tok.getLexeme())==false){
                            ((Pila)e2).push(tok.getLexeme(),tok.getLexeme());
                        }else{
                            errorParametroDuplicado(e1);
                        }
                    }
                    RESULT = e2;
                
              CUP$parserSQFORM$result = parser.getSymbolFactory().newSymbol("camposProyectar",2, ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.elementAt(CUP$parserSQFORM$top-1)), ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), RESULT);
            }
          return CUP$parserSQFORM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // camposProyectar ::= error 
            {
              Object RESULT =null;

              CUP$parserSQFORM$result = parser.getSymbolFactory().newSymbol("camposProyectar",2, ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), RESULT);
            }
          return CUP$parserSQFORM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // camposProyectarP ::= COMA camposProyectar 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parserSQFORM$stack.peek()).value;
		
                        RESULT = e1;
                    
              CUP$parserSQFORM$result = parser.getSymbolFactory().newSymbol("camposProyectarP",4, ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.elementAt(CUP$parserSQFORM$top-1)), ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), RESULT);
            }
          return CUP$parserSQFORM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // camposProyectarP ::= 
            {
              Object RESULT =null;
		
                        RESULT = new Pila();
                    
              CUP$parserSQFORM$result = parser.getSymbolFactory().newSymbol("camposProyectarP",4, ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), RESULT);
            }
          return CUP$parserSQFORM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // camposProyectarP ::= error 
            {
              Object RESULT =null;

              CUP$parserSQFORM$result = parser.getSymbolFactory().newSymbol("camposProyectarP",4, ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), RESULT);
            }
          return CUP$parserSQFORM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // condicional ::= WHERE C_A clausula C_C 
            {
              Object RESULT =null;

              CUP$parserSQFORM$result = parser.getSymbolFactory().newSymbol("condicional",3, ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.elementAt(CUP$parserSQFORM$top-3)), ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), RESULT);
            }
          return CUP$parserSQFORM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // condicional ::= error 
            {
              Object RESULT =null;

              CUP$parserSQFORM$result = parser.getSymbolFactory().newSymbol("condicional",3, ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), RESULT);
            }
          return CUP$parserSQFORM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // clausula ::= ID operador varComparacion clausulap 
            {
              Object RESULT =null;

              CUP$parserSQFORM$result = parser.getSymbolFactory().newSymbol("clausula",5, ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.elementAt(CUP$parserSQFORM$top-3)), ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), RESULT);
            }
          return CUP$parserSQFORM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // clausula ::= PARAM operador varComparacion clausulap 
            {
              Object RESULT =null;

              CUP$parserSQFORM$result = parser.getSymbolFactory().newSymbol("clausula",5, ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.elementAt(CUP$parserSQFORM$top-3)), ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), RESULT);
            }
          return CUP$parserSQFORM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // clausula ::= error 
            {
              Object RESULT =null;

              CUP$parserSQFORM$result = parser.getSymbolFactory().newSymbol("clausula",5, ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), RESULT);
            }
          return CUP$parserSQFORM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // clausulap ::= logica clausula 
            {
              Object RESULT =null;

              CUP$parserSQFORM$result = parser.getSymbolFactory().newSymbol("clausulap",6, ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.elementAt(CUP$parserSQFORM$top-1)), ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), RESULT);
            }
          return CUP$parserSQFORM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // clausulap ::= 
            {
              Object RESULT =null;

              CUP$parserSQFORM$result = parser.getSymbolFactory().newSymbol("clausulap",6, ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), RESULT);
            }
          return CUP$parserSQFORM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // clausulap ::= error 
            {
              Object RESULT =null;

              CUP$parserSQFORM$result = parser.getSymbolFactory().newSymbol("clausulap",6, ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), RESULT);
            }
          return CUP$parserSQFORM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // logica ::= OR 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parserSQFORM$stack.peek()).value;
		
            RESULT =e1;
        
              CUP$parserSQFORM$result = parser.getSymbolFactory().newSymbol("logica",7, ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), RESULT);
            }
          return CUP$parserSQFORM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // logica ::= NOT 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parserSQFORM$stack.peek()).value;
		
            RESULT =e1;
        
              CUP$parserSQFORM$result = parser.getSymbolFactory().newSymbol("logica",7, ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), RESULT);
            }
          return CUP$parserSQFORM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // logica ::= AND 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parserSQFORM$stack.peek()).value;
		
            RESULT =e1;
        
              CUP$parserSQFORM$result = parser.getSymbolFactory().newSymbol("logica",7, ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), RESULT);
            }
          return CUP$parserSQFORM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // logica ::= error 
            {
              Object RESULT =null;

              CUP$parserSQFORM$result = parser.getSymbolFactory().newSymbol("logica",7, ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), RESULT);
            }
          return CUP$parserSQFORM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // operador ::= ME_Q 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parserSQFORM$stack.peek()).value;
		
                RESULT = e1;
            
              CUP$parserSQFORM$result = parser.getSymbolFactory().newSymbol("operador",9, ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), RESULT);
            }
          return CUP$parserSQFORM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // operador ::= MA_Q 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parserSQFORM$stack.peek()).value;
		
                RESULT = e1;
            
              CUP$parserSQFORM$result = parser.getSymbolFactory().newSymbol("operador",9, ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), RESULT);
            }
          return CUP$parserSQFORM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // operador ::= ME_EQ 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parserSQFORM$stack.peek()).value;
		
                RESULT = e1;
            
              CUP$parserSQFORM$result = parser.getSymbolFactory().newSymbol("operador",9, ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), RESULT);
            }
          return CUP$parserSQFORM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // operador ::= MA_EQ 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parserSQFORM$stack.peek()).value;
		
                RESULT = e1;
            
              CUP$parserSQFORM$result = parser.getSymbolFactory().newSymbol("operador",9, ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), RESULT);
            }
          return CUP$parserSQFORM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // operador ::= EQ 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parserSQFORM$stack.peek()).value;
		
                RESULT = e1;
            
              CUP$parserSQFORM$result = parser.getSymbolFactory().newSymbol("operador",9, ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), RESULT);
            }
          return CUP$parserSQFORM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // operador ::= ME_Q_MA_Q 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parserSQFORM$stack.peek()).value;
		
                RESULT = e1;
            
              CUP$parserSQFORM$result = parser.getSymbolFactory().newSymbol("operador",9, ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), RESULT);
            }
          return CUP$parserSQFORM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // operador ::= error 
            {
              Object RESULT =null;

              CUP$parserSQFORM$result = parser.getSymbolFactory().newSymbol("operador",9, ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), RESULT);
            }
          return CUP$parserSQFORM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // varComparacion ::= NUM 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parserSQFORM$stack.peek()).value;
		
                    RESULT = e1;
                
              CUP$parserSQFORM$result = parser.getSymbolFactory().newSymbol("varComparacion",8, ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), RESULT);
            }
          return CUP$parserSQFORM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // varComparacion ::= VALUE 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parserSQFORM$stack.peek()).value;
		
                    RESULT = e1;
                
              CUP$parserSQFORM$result = parser.getSymbolFactory().newSymbol("varComparacion",8, ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), RESULT);
            }
          return CUP$parserSQFORM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // varComparacion ::= error 
            {
              Object RESULT =null;

              CUP$parserSQFORM$result = parser.getSymbolFactory().newSymbol("varComparacion",8, ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserSQFORM$stack.peek()), RESULT);
            }
          return CUP$parserSQFORM$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parserSQFORM$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parserSQFORM$do_action(
    int                        CUP$parserSQFORM$act_num,
    java_cup.runtime.lr_parser CUP$parserSQFORM$parser,
    java.util.Stack            CUP$parserSQFORM$stack,
    int                        CUP$parserSQFORM$top)
    throws java.lang.Exception
    {
              return CUP$parserSQFORM$do_action_part00000000(
                               CUP$parserSQFORM$act_num,
                               CUP$parserSQFORM$parser,
                               CUP$parserSQFORM$stack,
                               CUP$parserSQFORM$top);
    }
}

}
