/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.carlos.app_cliente_proyecto1.UI;

import com.carlos.app_cliente_proyecto1.HttpMethods.enviarInfo;
import com.carlos.app_cliente_proyecto1.Lexer.lexerImportar;
import com.carlos.app_cliente_proyecto1.Objetos.Formulario;
import com.carlos.app_cliente_proyecto1.Parser.parserImportar;
import com.carlos.app_cliente_proyecto1.conversionIndigo.FormularioToIndigo;
import java.io.File;
import java.io.FileReader;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author benjamin
 */
public class CargarFormularios extends javax.swing.JInternalFrame {
    
    private FormularioToIndigo convertir = new FormularioToIndigo();
    private enviarInfo enviarServidor = new enviarInfo();
    
    /**
     * Creates new form CargarFormularios
     */
    public CargarFormularios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelServidor = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnEnviarForm = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        panelErrores = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setClosable(true);
        setIconifiable(true);

        panelServidor.setEditable(false);
        panelServidor.setColumns(20);
        panelServidor.setRows(5);
        panelServidor.setTabSize(3);
        jScrollPane1.setViewportView(panelServidor);

        jLabel1.setText("Carga de Formulario");

        jButton1.setText("Buscar Formulario");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Archivo");

        btnEnviarForm.setText("Enviar Formulario");
        btnEnviarForm.setEnabled(false);

        jLabel4.setText("Info del Archivo");

        panelErrores.setEditable(false);
        panelErrores.setColumns(20);
        panelErrores.setRows(5);
        panelErrores.setTabSize(3);
        jScrollPane2.setViewportView(panelErrores);

        jLabel5.setText("Respuesta del Servidor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton1)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel3))
                    .addComponent(btnEnviarForm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(40, 40, 40)
                .addComponent(btnEnviarForm)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Formulario .form", "form");
        chooser.setFileFilter(filtro);
        int retorno = chooser.showOpenDialog(this);
        if (retorno == JFileChooser.APPROVE_OPTION) {
            analizararchivo(chooser.getSelectedFile());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void analizararchivo(File archivo) {
        try {

            lexerImportar lex = new lexerImportar(new FileReader(archivo));
            parserImportar parser = new parserImportar(lex);
            parser.parse();

            mostarErrores(lex.getErrorsList(), parser.getErrorsList());
            List<Formulario> formularios = parser.getFormularios();

            if (btnEnviarForm.isEnabled()) {
                panelErrores.setText(panelErrores.getText()+"\n"+convertir.convertir(formularios));
                panelServidor.setText(enviarServidor.envioRespuesta(convertir.convertir(formularios)));
            }

        } catch (Exception e) {
            System.out.println("Error en importar leer importar archivo");
            e.printStackTrace();
        }
    }

    public void mostarErrores(List<String> lexicos, List<String> sintacticos) {
        String lineas = "";

        if (!lexicos.isEmpty()) {
            lineas = lineas + "Errores lexicos encontrados:\n";
            for (String lexico : lexicos) {
                lineas = lineas + lexico + "\n";
            }
        }
        if (!sintacticos.isEmpty()) {
            lineas = lineas + "Errores sintacticos encontrados:\n";
            for (String sintactico : sintacticos) {
                lineas = lineas + sintactico + "\n";
            }
        }
        if (lineas.isEmpty()) {
            lineas = "Archivo correcto, conversion a indigo: ";
            btnEnviarForm.setEnabled(true);
        } else {
            btnEnviarForm.setEnabled(false);
        }

        panelErrores.setText(lineas);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviarForm;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea panelErrores;
    private javax.swing.JTextArea panelServidor;
    // End of variables declaration//GEN-END:variables
}
