/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.carlos.app_cliente_proyecto1.UI;

import com.carlos.app_cliente_proyecto1.HttpMethods.enviarInfo;
import com.carlos.app_cliente_proyecto1.HttpMethods.importarForm;
import com.carlos.app_cliente_proyecto1.conversionIndigo.FormularioToIndigo;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.InputStreamReader;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author benjamin
 */
public class CargarFormularios extends javax.swing.JInternalFrame {

    private FormularioToIndigo convertir = new FormularioToIndigo();
    private enviarInfo enviarServidor = new enviarInfo();
    private String code = "";

    /**
     * Creates new form CargarFormularios
     */
    public CargarFormularios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelServidor = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnEnviarForm = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setClosable(true);
        setIconifiable(true);

        panelServidor.setEditable(false);
        panelServidor.setColumns(20);
        panelServidor.setRows(5);
        panelServidor.setTabSize(3);
        jScrollPane1.setViewportView(panelServidor);

        jLabel1.setText("Carga de Formulario");

        jButton1.setText("Buscar Formulario");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Archivo");

        btnEnviarForm.setText("Enviar Formulario");
        btnEnviarForm.setEnabled(false);
        btnEnviarForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarFormActionPerformed(evt);
            }
        });

        jLabel5.setText("Respuesta del Servidor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton1)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel3))
                    .addComponent(btnEnviarForm))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(40, 40, 40)
                        .addComponent(btnEnviarForm))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Formulario .form", "form");
        chooser.setFileFilter(filtro);
        int retorno = chooser.showOpenDialog(this);
        if (retorno == JFileChooser.APPROVE_OPTION) {
            lecArchivo(chooser.getSelectedFile());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnEnviarFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarFormActionPerformed
        // TODO add your handling code here:
        try {
            importarForm importar = new importarForm();
            String respuesta = "";
            respuesta = importar.enviarForm(this.code.toString());
            if (respuesta == null) {
                this.panelServidor.setText("Servidor no disponible!!!");
            } else {
                this.panelServidor.setText(respuesta);
                this.btnEnviarForm.setEnabled(false);
            }
        } catch (Exception e) {
            System.out.println("Error al importar el formulario");
        }

    }//GEN-LAST:event_btnEnviarFormActionPerformed

    private void lecArchivo(File archivo) {
        try {

            StringBuilder resultado = new StringBuilder();
            BufferedReader rd = new BufferedReader(new FileReader(archivo));
            importarForm importar = new importarForm();
            String linea;

            while ((linea = rd.readLine()) != null) {
                resultado.append(linea + "\n");
            }

            System.out.println(resultado.toString());
            if (!resultado.toString().isEmpty()) {
                btnEnviarForm.setEnabled(true);
                code = resultado.toString();
            } else {
                btnEnviarForm.setEnabled(false);
            }

        } catch (Exception e) {
            System.out.println("Error el lectura de archivo");
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviarForm;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea panelServidor;
    // End of variables declaration//GEN-END:variables
}
