
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.carlos.app_cliente_proyecto1.Parser;

/** CUP generated class containing symbol constants. */
public class parserImportarSym {
  /* terminals */
  public static final int CAMP_TEXT = 23;
  public static final int FORM = 13;
  public static final int P_C = 5;
  public static final int BOTON = 30;
  public static final int REQUE = 18;
  public static final int P_A = 4;
  public static final int ESTRUCT = 42;
  public static final int ASIGNACION_NUM = 37;
  public static final int NAME_CAMP = 12;
  public static final int TEXT_VIEW = 16;
  public static final int CENT = 31;
  public static final int NEW_FORM = 40;
  public static final int ID_FORM = 41;
  public static final int NOT = 36;
  public static final int YES = 35;
  public static final int OPTION = 19;
  public static final int IZQ = 32;
  public static final int IND = 15;
  public static final int CLASS = 14;
  public static final int ID = 8;
  public static final int L_C = 3;
  public static final int EOF = 0;
  public static final int L_A = 2;
  public static final int error = 1;
  public static final int JUST = 34;
  public static final int CHECK = 25;
  public static final int URL = 22;
  public static final int ASIG_ID = 7;
  public static final int NAME = 10;
  public static final int ASIGNACION = 38;
  public static final int COM = 6;
  public static final int IMG = 28;
  public static final int RADIO = 26;
  public static final int TITLE = 9;
  public static final int THEME = 11;
  public static final int TEXT_AREA = 24;
  public static final int COLM = 21;
  public static final int DER = 33;
  public static final int ASIGNACION_ESP = 39;
  public static final int FILE = 27;
  public static final int COMBO = 29;
  public static final int D_DOT = 43;
  public static final int ALI = 17;
  public static final int FILAS = 20;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "L_A",
  "L_C",
  "P_A",
  "P_C",
  "COM",
  "ASIG_ID",
  "ID",
  "TITLE",
  "NAME",
  "THEME",
  "NAME_CAMP",
  "FORM",
  "CLASS",
  "IND",
  "TEXT_VIEW",
  "ALI",
  "REQUE",
  "OPTION",
  "FILAS",
  "COLM",
  "URL",
  "CAMP_TEXT",
  "TEXT_AREA",
  "CHECK",
  "RADIO",
  "FILE",
  "IMG",
  "COMBO",
  "BOTON",
  "CENT",
  "IZQ",
  "DER",
  "JUST",
  "YES",
  "NOT",
  "ASIGNACION_NUM",
  "ASIGNACION",
  "ASIGNACION_ESP",
  "NEW_FORM",
  "ID_FORM",
  "ESTRUCT",
  "D_DOT"
  };
}

