
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.carlos.app_cliente_proyecto1.Parser;

import com.carlos.app_cliente_proyecto1.Lexer.lexerIndigo;
import java.util.ArrayList;
import java_cup.runtime.Symbol;
import java.util.List;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parserIndigo extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return parserIndigoSym.class;
}

  /** Default constructor. */
  @Deprecated
  public parserIndigo() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parserIndigo(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parserIndigo(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\106\000\002\002\004\000\002\002\005\000\002\003" +
    "\007\000\002\005\003\000\002\005\002\000\002\004\020" +
    "\000\002\004\020\000\002\004\020\000\002\004\020\000" +
    "\002\004\020\000\002\004\020\000\002\004\020\000\002" +
    "\004\020\000\002\004\020\000\002\020\006\000\002\021" +
    "\004\000\002\021\002\000\002\006\006\000\002\006\006" +
    "\000\002\006\006\000\002\007\007\000\002\007\007\000" +
    "\002\012\006\000\002\012\002\000\002\013\006\000\002" +
    "\010\007\000\002\010\007\000\002\014\006\000\002\014" +
    "\002\000\002\015\006\000\002\011\007\000\002\011\007" +
    "\000\002\016\006\000\002\017\006\000\002\022\006\000" +
    "\002\032\004\000\002\032\002\000\002\033\006\000\002" +
    "\033\006\000\002\033\006\000\002\033\006\000\002\034" +
    "\007\000\002\034\007\000\002\034\007\000\002\035\007" +
    "\000\002\035\007\000\002\035\007\000\002\036\007\000" +
    "\002\036\007\000\002\036\007\000\002\037\007\000\002" +
    "\037\007\000\002\037\007\000\002\040\007\000\002\040" +
    "\007\000\002\041\007\000\002\041\007\000\002\042\007" +
    "\000\002\042\007\000\002\043\007\000\002\043\007\000" +
    "\002\044\007\000\002\044\007\000\002\045\007\000\002" +
    "\045\007\000\002\046\006\000\002\047\006\000\002\050" +
    "\006\000\002\051\006\000\002\051\002" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\u015f\000\004\011\004\001\002\000\004\004\007\001" +
    "\002\000\004\002\006\001\002\000\004\002\001\001\002" +
    "\000\004\006\012\001\002\000\004\012\011\001\002\000" +
    "\004\002\000\001\002\000\004\007\013\001\002\000\004" +
    "\014\014\001\002\000\024\021\022\030\017\031\025\033" +
    "\015\034\021\035\026\036\020\037\023\040\016\001\002" +
    "\000\004\005\u0155\001\002\000\004\005\u0148\001\002\000" +
    "\004\005\253\001\002\000\004\005\236\001\002\000\004" +
    "\005\221\001\002\000\004\005\077\001\002\000\004\005" +
    "\062\001\002\000\004\012\uffff\001\002\000\004\005\045" +
    "\001\002\000\004\005\027\001\002\000\004\017\030\001" +
    "\002\000\004\065\031\001\002\000\004\014\032\001\002" +
    "\000\004\015\033\001\002\000\002\001\002\000\004\016" +
    "\035\001\002\000\004\020\036\001\002\000\004\004\037" +
    "\001\002\000\004\010\040\001\002\000\004\006\041\001" +
    "\002\000\004\005\042\001\002\000\006\004\007\012\ufffd" +
    "\001\002\000\004\012\ufff7\001\002\000\004\012\ufffe\001" +
    "\002\000\004\017\046\001\002\000\004\026\047\001\002" +
    "\000\004\014\050\001\002\000\004\015\051\001\002\000" +
    "\002\001\002\000\004\016\053\001\002\000\004\020\054" +
    "\001\002\000\004\004\055\001\002\000\004\010\056\001" +
    "\002\000\004\006\057\001\002\000\004\005\060\001\002" +
    "\000\006\004\007\012\ufffd\001\002\000\004\012\ufffa\001" +
    "\002\000\004\017\063\001\002\000\004\027\064\001\002" +
    "\000\004\014\065\001\002\000\004\015\066\001\002\000" +
    "\002\001\002\000\004\016\070\001\002\000\004\020\071" +
    "\001\002\000\004\004\072\001\002\000\004\010\073\001" +
    "\002\000\004\006\074\001\002\000\004\005\075\001\002" +
    "\000\006\004\007\012\ufffd\001\002\000\004\012\ufff5\001" +
    "\002\000\004\017\100\001\002\000\004\026\101\001\002" +
    "\000\004\014\102\001\002\000\004\015\103\001\002\000" +
    "\004\017\105\001\002\000\004\016\212\001\002\000\010" +
    "\022\111\023\106\024\110\001\002\000\004\014\166\001" +
    "\002\000\004\020\162\001\002\000\004\014\136\001\002" +
    "\000\004\014\112\001\002\000\004\025\113\001\002\000" +
    "\004\013\115\001\002\000\004\020\ufff0\001\002\000\006" +
    "\023\116\024\117\001\002\000\004\014\127\001\002\000" +
    "\004\014\120\001\002\000\004\025\121\001\002\000\004" +
    "\013\123\001\002\000\004\020\uffec\001\002\000\004\023" +
    "\124\001\002\000\004\014\125\001\002\000\004\025\126" +
    "\001\002\000\004\020\uffe9\001\002\000\004\025\130\001" +
    "\002\000\006\013\132\020\uffea\001\002\000\004\020\uffed" +
    "\001\002\000\004\024\133\001\002\000\004\014\134\001" +
    "\002\000\004\025\135\001\002\000\004\020\uffeb\001\002" +
    "\000\004\025\137\001\002\000\004\013\141\001\002\000" +
    "\004\020\uffee\001\002\000\006\022\143\023\142\001\002" +
    "\000\004\014\153\001\002\000\004\014\144\001\002\000" +
    "\004\025\145\001\002\000\004\013\147\001\002\000\004" +
    "\020\uffe3\001\002\000\004\023\150\001\002\000\004\014" +
    "\151\001\002\000\004\025\152\001\002\000\004\020\uffe1" +
    "\001\002\000\004\025\154\001\002\000\004\013\155\001" +
    "\002\000\004\022\157\001\002\000\004\020\uffe2\001\002" +
    "\000\004\014\160\001\002\000\004\025\161\001\002\000" +
    "\004\020\uffe0\001\002\000\006\013\164\016\ufff1\001\002" +
    "\000\004\016\ufff3\001\002\000\004\017\105\001\002\000" +
    "\004\016\ufff2\001\002\000\004\025\167\001\002\000\004" +
    "\013\171\001\002\000\004\020\uffef\001\002\000\006\022" +
    "\173\024\172\001\002\000\004\014\203\001\002\000\004" +
    "\014\174\001\002\000\004\025\175\001\002\000\006\013" +
    "\177\020\uffe5\001\002\000\004\020\uffe8\001\002\000\004" +
    "\024\200\001\002\000\004\014\201\001\002\000\004\025" +
    "\202\001\002\000\004\020\uffe6\001\002\000\004\025\204" +
    "\001\002\000\004\013\206\001\002\000\004\020\uffe7\001" +
    "\002\000\004\022\207\001\002\000\004\014\210\001\002" +
    "\000\004\025\211\001\002\000\004\020\uffe4\001\002\000" +
    "\004\020\213\001\002\000\004\004\214\001\002\000\004" +
    "\010\215\001\002\000\004\006\216\001\002\000\004\005" +
    "\217\001\002\000\006\004\007\012\ufffd\001\002\000\004" +
    "\012\ufffc\001\002\000\004\017\222\001\002\000\004\065" +
    "\223\001\002\000\004\014\224\001\002\000\004\015\225" +
    "\001\002\000\002\001\002\000\004\016\227\001\002\000" +
    "\004\020\230\001\002\000\004\004\231\001\002\000\004" +
    "\010\232\001\002\000\004\006\233\001\002\000\004\005" +
    "\234\001\002\000\006\004\007\012\ufffd\001\002\000\004" +
    "\012\ufff8\001\002\000\004\017\237\001\002\000\004\027" +
    "\240\001\002\000\004\014\241\001\002\000\004\015\242" +
    "\001\002\000\002\001\002\000\004\016\244\001\002\000" +
    "\004\020\245\001\002\000\004\004\246\001\002\000\004" +
    "\010\247\001\002\000\004\006\250\001\002\000\004\005" +
    "\251\001\002\000\006\004\007\012\ufffd\001\002\000\004" +
    "\012\ufff6\001\002\000\004\017\254\001\002\000\004\026" +
    "\255\001\002\000\004\014\256\001\002\000\004\015\257" +
    "\001\002\000\004\017\261\001\002\000\004\016\u0141\001" +
    "\002\000\012\041\266\042\264\043\262\044\265\001\002" +
    "\000\004\014\u0131\001\002\000\004\020\u012d\001\002\000" +
    "\004\014\u0114\001\002\000\004\014\356\001\002\000\004" +
    "\014\267\001\002\000\004\025\270\001\002\000\004\013" +
    "\272\001\002\000\004\020\uffdc\001\002\000\010\042\274" +
    "\043\273\044\275\001\002\000\004\014\342\001\002\000" +
    "\004\014\322\001\002\000\004\014\276\001\002\000\004" +
    "\025\277\001\002\000\004\013\301\001\002\000\004\020" +
    "\uffd6\001\002\000\006\042\303\043\302\001\002\000\004" +
    "\014\313\001\002\000\004\014\304\001\002\000\004\025" +
    "\305\001\002\000\004\013\307\001\002\000\004\020\uffc2" +
    "\001\002\000\004\043\310\001\002\000\004\014\311\001" +
    "\002\000\004\025\312\001\002\000\004\020\uffbe\001\002" +
    "\000\004\025\314\001\002\000\004\013\316\001\002\000" +
    "\004\020\uffc1\001\002\000\004\042\317\001\002\000\004" +
    "\014\320\001\002\000\004\025\321\001\002\000\004\020" +
    "\uffbf\001\002\000\004\025\323\001\002\000\004\013\325" +
    "\001\002\000\004\020\uffd8\001\002\000\006\043\326\044" +
    "\327\001\002\000\004\014\333\001\002\000\004\014\330" +
    "\001\002\000\004\025\331\001\002\000\004\013\307\001" +
    "\002\000\004\020\uffcb\001\002\000\004\025\334\001\002" +
    "\000\006\013\336\020\uffbc\001\002\000\004\020\uffcc\001" +
    "\002\000\004\044\337\001\002\000\004\014\340\001\002" +
    "\000\004\025\341\001\002\000\004\020\uffbd\001\002\000" +
    "\004\025\343\001\002\000\004\013\345\001\002\000\004" +
    "\020\uffd7\001\002\000\006\043\346\044\347\001\002\000" +
    "\004\014\353\001\002\000\004\014\350\001\002\000\004" +
    "\025\351\001\002\000\004\013\307\001\002\000\004\020" +
    "\uffc5\001\002\000\004\025\354\001\002\000\006\013\336" +
    "\020\uffbc\001\002\000\004\020\uffc6\001\002\000\004\025" +
    "\357\001\002\000\004\013\361\001\002\000\004\020\uffd9" +
    "\001\002\000\010\041\364\042\363\043\362\001\002\000" +
    "\004\014\u0108\001\002\000\004\014\370\001\002\000\004" +
    "\014\365\001\002\000\004\025\366\001\002\000\004\013" +
    "\301\001\002\000\004\020\uffcf\001\002\000\004\025\371" +
    "\001\002\000\004\013\373\001\002\000\004\020\uffce\001" +
    "\002\000\006\041\375\043\374\001\002\000\004\014\u0101" +
    "\001\002\000\004\014\376\001\002\000\004\025\377\001" +
    "\002\000\004\013\307\001\002\000\004\020\uffc8\001\002" +
    "\000\004\025\u0102\001\002\000\004\013\u0104\001\002\000" +
    "\004\020\uffc7\001\002\000\004\041\u0105\001\002\000\004" +
    "\014\u0106\001\002\000\004\025\u0107\001\002\000\004\020" +
    "\uffc0\001\002\000\004\025\u0109\001\002\000\004\013\u010b" +
    "\001\002\000\004\020\uffcd\001\002\000\006\041\u010d\042" +
    "\u010c\001\002\000\004\014\u0111\001\002\000\004\014\u010e" +
    "\001\002\000\004\025\u010f\001\002\000\004\013\316\001" +
    "\002\000\004\020\uffc4\001\002\000\004\025\u0112\001\002" +
    "\000\004\013\u0104\001\002\000\004\020\uffc3\001\002\000" +
    "\004\025\u0115\001\002\000\004\013\u0117\001\002\000\004" +
    "\020\uffdb\001\002\000\010\041\u011a\043\u0118\044\u0119\001" +
    "\002\000\004\014\u0121\001\002\000\004\014\u011e\001\002" +
    "\000\004\014\u011b\001\002\000\004\025\u011c\001\002\000" +
    "\004\013\325\001\002\000\004\020\uffd5\001\002\000\004" +
    "\025\u011f\001\002\000\004\013\373\001\002\000\004\020" +
    "\uffd3\001\002\000\004\025\u0122\001\002\000\004\013\u0124" +
    "\001\002\000\004\020\uffd4\001\002\000\006\041\u0126\044" +
    "\u0125\001\002\000\004\014\u012a\001\002\000\004\014\u0127" +
    "\001\002\000\004\025\u0128\001\002\000\006\013\336\020" +
    "\uffbc\001\002\000\004\020\uffca\001\002\000\004\025\u012b" +
    "\001\002\000\004\013\u0104\001\002\000\004\020\uffc9\001" +
    "\002\000\006\013\u012f\016\uffdd\001\002\000\004\016\uffdf" +
    "\001\002\000\004\017\261\001\002\000\004\016\uffde\001" +
    "\002\000\004\025\u0132\001\002\000\004\013\u0134\001\002" +
    "\000\004\020\uffda\001\002\000\010\041\u0137\042\u0135\044" +
    "\u0136\001\002\000\004\014\u013e\001\002\000\004\014\u013b" +
    "\001\002\000\004\014\u0138\001\002\000\004\025\u0139\001" +
    "\002\000\004\013\325\001\002\000\004\020\uffd2\001\002" +
    "\000\004\025\u013c\001\002\000\004\013\u010b\001\002\000" +
    "\004\020\uffd0\001\002\000\004\025\u013f\001\002\000\004" +
    "\013\u0124\001\002\000\004\020\uffd1\001\002\000\004\020" +
    "\u0142\001\002\000\004\004\u0143\001\002\000\004\010\u0144" +
    "\001\002\000\004\006\u0145\001\002\000\004\005\u0146\001" +
    "\002\000\006\004\007\012\ufffd\001\002\000\004\012\ufffb" +
    "\001\002\000\004\020\u0149\001\002\000\004\027\u014a\001" +
    "\002\000\004\014\u014b\001\002\000\004\015\u014c\001\002" +
    "\000\002\001\002\000\004\016\u014e\001\002\000\004\020" +
    "\u014f\001\002\000\004\004\u0150\001\002\000\004\010\u0151" +
    "\001\002\000\004\006\u0152\001\002\000\004\005\u0153\001" +
    "\002\000\006\004\007\012\ufffd\001\002\000\004\012\ufff4" +
    "\001\002\000\004\017\u0156\001\002\000\004\065\u0157\001" +
    "\002\000\004\014\u0158\001\002\000\004\015\u0159\001\002" +
    "\000\002\001\002\000\004\016\u015b\001\002\000\004\020" +
    "\u015c\001\002\000\004\004\u015d\001\002\000\004\010\u015e" +
    "\001\002\000\004\006\u015f\001\002\000\004\005\u0160\001" +
    "\002\000\006\004\007\012\ufffd\001\002\000\004\012\ufff9" +
    "\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\u015f\000\004\002\004\001\001\000\004\003\007\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\004\023\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\026\033\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\003\043\005\042\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\023" +
    "\051\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\003\043\005\060\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\030\066\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\003\043\005\075" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\020\103" +
    "\001\001\000\002\001\001\000\004\006\106\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\007\113\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\013\121\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\012" +
    "\130\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\011\137\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\016\145\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\017\155\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\021\162\001\001\000\002" +
    "\001\001\000\004\020\164\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\010\167\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\014\175\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\015\204\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\003\043\005\217\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\025\225\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\003\043\005\234" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\027\242" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\003\043\005\251\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\022\257\001\001\000\002\001\001\000" +
    "\004\033\262\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\034\270\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\045\277\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\050\305\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\047\314\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\040\323\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\050\331\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\051\334\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\043\343\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\050\351\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\051\354\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\037\357" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\045\366\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\042\371\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\050\377\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\046\u0102\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\044\u0109\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\047\u010f\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\046\u0112\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\035\u0115\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\040\u011c\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\042\u011f\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\041\u0122\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\051\u0128\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\046\u012b\001\001\000\002\001\001\000" +
    "\004\032\u012d\001\001\000\002\001\001\000\004\022\u012f" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\036" +
    "\u0132\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\040\u0139\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\044\u013c\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\041\u013f\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\003\043\005\u0146" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\031\u014c" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\003\043\005\u0153\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\024\u0159\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\003\043\005\u0160\001" +
    "\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parserIndigo$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parserIndigo$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parserIndigo$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



        private List<String> errorsList = new ArrayList();

        public parserIndigo(lexerIndigo lex){
                super(lex);
        }

        public void report_error(String message, Object info){
                System.out.println("reporterror");
        }

        public void report_fatal_error(String message, Object info){
                System.out.println(info.toString());
                System.out.println("reportfatal");
        }
        /*
        public void syntax_error(Symbol cur_token){
                
                System.out.println("Error sintactico");       
        }
        */
        protected int error_sync_size() {
		return 1;
	}
        public List<String> getErrorsList(){
	        return errorsList
	        ;
	}



/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parserIndigo$actions {
  private final parserIndigo parser;

  /** Constructor */
  CUP$parserIndigo$actions(parserIndigo parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parserIndigo$do_action_part00000000(
    int                        CUP$parserIndigo$act_num,
    java_cup.runtime.lr_parser CUP$parserIndigo$parser,
    java.util.Stack            CUP$parserIndigo$stack,
    int                        CUP$parserIndigo$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parserIndigo$result;

      /* select the action based on the action number */
      switch (CUP$parserIndigo$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= inicio EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-1)).value;
		RESULT = start_val;
              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-1)), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parserIndigo$parser.done_parsing();
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // inicio ::= SSS contenido FSS 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("inicio",0, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-2)), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // contenido ::= ME_Q ADM SS D_DOT type_s 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("contenido",1, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-4)), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // contenido1 ::= contenido 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("contenido1",3, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // contenido1 ::= 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("contenido1",3, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // type_s ::= CR_U MA_Q L_A CREDEN_USER D_DOT C_A parametros C_C L_C ME_Q FS ADM MA_Q contenido1 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("type_s",2, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-13)), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // type_s ::= MO_U MA_Q L_A CREDEN_USER D_DOT C_A paramsMO_U C_C L_C ME_Q FS ADM MA_Q contenido1 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("type_s",2, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-13)), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // type_s ::= DEL_U MA_Q L_A CREDEN_USER D_DOT C_A paramsDEL_U C_C L_C ME_Q FS ADM MA_Q contenido1 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("type_s",2, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-13)), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // type_s ::= NEW_F MA_Q L_A PARAMS_FORM D_DOT C_A paramsNEW_F C_C L_C ME_Q FS ADM MA_Q contenido1 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("type_s",2, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-13)), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // type_s ::= DEL_F MA_Q L_A PARAMS_FORM D_DOT C_A paramsDEL_F C_C L_C ME_Q FS ADM MA_Q contenido1 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("type_s",2, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-13)), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // type_s ::= MO_F MA_Q L_A PARAMS_FORM D_DOT C_A paramsMO_F C_C L_C ME_Q FS ADM MA_Q contenido1 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("type_s",2, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-13)), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // type_s ::= ADD_C MA_Q L_A PARAMS_COMP D_DOT C_A paramsADD_C C_C L_C ME_Q FS ADM MA_Q contenido1 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("type_s",2, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-13)), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // type_s ::= DEL_C MA_Q L_A PARAMS_COMP D_DOT C_A paramsDEL_C C_C L_C ME_Q FS ADM MA_Q contenido1 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("type_s",2, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-13)), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // type_s ::= MO_C MA_Q L_C PARAMS_COMP D_DOT C_A paramsMO_C C_C L_C ME_Q FS ADM MA_Q contenido1 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("type_s",2, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-13)), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // parametros ::= L_A cont_CR_U L_C parametros2 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("parametros",14, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-3)), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // parametros2 ::= COM parametros 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("parametros2",15, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-1)), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // parametros2 ::= 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("parametros2",15, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // cont_CR_U ::= USER D_DOT ASIGNACION cont_CR_U1 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("cont_CR_U",4, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-3)), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // cont_CR_U ::= PASS D_DOT ASIGNACION cont_CR_U2 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("cont_CR_U",4, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-3)), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // cont_CR_U ::= FECHA D_DOT ASIGNACION cont_CR_U3 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("cont_CR_U",4, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-3)), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // cont_CR_U1 ::= COM PASS D_DOT ASIGNACION cont_CR_U1_2 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("cont_CR_U1",5, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-4)), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // cont_CR_U1 ::= COM FECHA D_DOT ASIGNACION cont_CR_U1_3 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("cont_CR_U1",5, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-4)), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // cont_CR_U1_2 ::= COM FECHA D_DOT ASIGNACION 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("cont_CR_U1_2",8, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-3)), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // cont_CR_U1_2 ::= 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("cont_CR_U1_2",8, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // cont_CR_U1_3 ::= COM PASS D_DOT ASIGNACION 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("cont_CR_U1_3",9, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-3)), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // cont_CR_U2 ::= COM USER D_DOT ASIGNACION cont_CR_U2_2 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("cont_CR_U2",6, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-4)), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // cont_CR_U2 ::= COM FECHA D_DOT ASIGNACION cont_CR_U2_3 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("cont_CR_U2",6, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-4)), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // cont_CR_U2_2 ::= COM FECHA D_DOT ASIGNACION 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("cont_CR_U2_2",10, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-3)), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // cont_CR_U2_2 ::= 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("cont_CR_U2_2",10, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // cont_CR_U2_3 ::= COM USER D_DOT ASIGNACION 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("cont_CR_U2_3",11, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-3)), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // cont_CR_U3 ::= COM USER D_DOT ASIGNACION cont_CR_U3_2 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("cont_CR_U3",7, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-4)), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // cont_CR_U3 ::= COM PASS D_DOT ASIGNACION cont_CR_U3_3 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("cont_CR_U3",7, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-4)), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // cont_CR_U3_2 ::= COM PASS D_DOT ASIGNACION 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("cont_CR_U3_2",12, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-3)), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // cont_CR_U3_3 ::= COM USER D_DOT ASIGNACION 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("cont_CR_U3_3",13, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-3)), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // paramsMO_U ::= L_A contMO_U L_C paramsMO_U2 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("paramsMO_U",16, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-3)), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // paramsMO_U2 ::= COM paramsMO_U 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("paramsMO_U2",24, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-1)), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // paramsMO_U2 ::= 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("paramsMO_U2",24, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // contMO_U ::= USER_ANT D_DOT ASIGNACION contMO_U1 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("contMO_U",25, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-3)), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // contMO_U ::= USER_NEW D_DOT ASIGNACION contMO_U2 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("contMO_U",25, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-3)), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // contMO_U ::= PASS_NEW D_DOT ASIGNACION contMO_U3 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("contMO_U",25, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-3)), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // contMO_U ::= FECHA_MOD D_DOT ASIGNACION contMO_U4 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("contMO_U",25, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-3)), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // contMO_U1 ::= COM USER_NEW D_DOT ASIGNACION contMO_U5 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("contMO_U1",26, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-4)), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // contMO_U1 ::= COM PASS_NEW D_DOT ASIGNACION contMO_U8 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("contMO_U1",26, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-4)), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // contMO_U1 ::= COM FECHA_MOD D_DOT ASIGNACION contMO_U11 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("contMO_U1",26, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-4)), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // contMO_U2 ::= COM USER_ANT D_DOT ASIGNACION contMO_U5 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("contMO_U2",27, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-4)), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // contMO_U2 ::= COM PASS_NEW D_DOT ASIGNACION contMO_U6 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("contMO_U2",27, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-4)), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // contMO_U2 ::= COM FECHA_MOD D_DOT ASIGNACION contMO_U7 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("contMO_U2",27, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-4)), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // contMO_U3 ::= COM USER_ANT D_DOT ASIGNACION contMO_U5 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("contMO_U3",28, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-4)), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // contMO_U3 ::= COM USER_NEW D_DOT ASIGNACION contMO_U6 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("contMO_U3",28, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-4)), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // contMO_U3 ::= COM FECHA_MOD D_DOT ASIGNACION contMO_U10 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("contMO_U3",28, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-4)), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // contMO_U4 ::= COM USER_ANT D_DOT ASIGNACION contMO_U11 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("contMO_U4",29, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-4)), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // contMO_U4 ::= COM USER_NEW D_DOT ASIGNACION contMO_U7 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("contMO_U4",29, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-4)), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // contMO_U4 ::= COM PASS_NEW D_DOT ASIGNACION contMO_U10 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("contMO_U4",29, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-4)), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // contMO_U5 ::= COM PASS_NEW D_DOT ASIGNACION contMO_U15 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("contMO_U5",30, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-4)), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // contMO_U5 ::= COM FECHA_MOD D_DOT ASIGNACION contMO_U14 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("contMO_U5",30, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-4)), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // contMO_U6 ::= COM USER_ANT D_DOT ASIGNACION contMO_U15 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("contMO_U6",31, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-4)), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // contMO_U6 ::= COM FECHA_MOD D_DOT ASIGNACION contMO_U12 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("contMO_U6",31, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-4)), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // contMO_U7 ::= COM USER_ANT D_DOT ASIGNACION contMO_U14 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("contMO_U7",32, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-4)), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // contMO_U7 ::= COM PASS_NEW D_DOT ASIGNACION contMO_U12 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("contMO_U7",32, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-4)), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // contMO_U8 ::= COM PASS_NEW D_DOT ASIGNACION contMO_U15 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("contMO_U8",33, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-4)), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // contMO_U8 ::= COM FECHA_MOD D_DOT ASIGNACION contMO_U14 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("contMO_U8",33, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-4)), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // contMO_U10 ::= COM USER_ANT D_DOT ASIGNACION contMO_U13 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("contMO_U10",34, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-4)), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // contMO_U10 ::= COM USER_NEW D_DOT ASIGNACION contMO_U12 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("contMO_U10",34, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-4)), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // contMO_U11 ::= COM USER_NEW D_DOT ASIGNACION contMO_U14 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("contMO_U11",35, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-4)), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // contMO_U11 ::= COM PASS_NEW D_DOT ASIGNACION contMO_U13 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("contMO_U11",35, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-4)), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // contMO_U12 ::= COM USER_ANT D_DOT ASIGNACION 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("contMO_U12",36, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-3)), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // contMO_U13 ::= COM USER_NEW D_DOT ASIGNACION 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("contMO_U13",37, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-3)), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // contMO_U14 ::= COM PASS_NEW D_DOT ASIGNACION 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("contMO_U14",38, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-3)), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // contMO_U15 ::= COM FECHA_MOD D_DOT ASIGNACION 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("contMO_U15",39, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.elementAt(CUP$parserIndigo$top-3)), ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // contMO_U15 ::= 
            {
              Object RESULT =null;

              CUP$parserIndigo$result = parser.getSymbolFactory().newSymbol("contMO_U15",39, ((java_cup.runtime.Symbol)CUP$parserIndigo$stack.peek()), RESULT);
            }
          return CUP$parserIndigo$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parserIndigo$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parserIndigo$do_action(
    int                        CUP$parserIndigo$act_num,
    java_cup.runtime.lr_parser CUP$parserIndigo$parser,
    java.util.Stack            CUP$parserIndigo$stack,
    int                        CUP$parserIndigo$top)
    throws java.lang.Exception
    {
              return CUP$parserIndigo$do_action_part00000000(
                               CUP$parserIndigo$act_num,
                               CUP$parserIndigo$parser,
                               CUP$parserIndigo$stack,
                               CUP$parserIndigo$top);
    }
}

}
