
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.carlos.app_cliente_proyecto1.Parser;

/** CUP generated class containing symbol constants. */
public class parserIndigoSym {
  /* terminals */
  public static final int FORM = 41;
  public static final int DEL_U = 23;
  public static final int REQUE = 46;
  public static final int SS = 5;
  public static final int PASS_NEW = 33;
  public static final int AGRE_C = 28;
  public static final int NAME_CAMP = 40;
  public static final int CR_U = 15;
  public static final int TEXT_VIEW = 44;
  public static final int USER_ANT = 31;
  public static final int NEW_F = 25;
  public static final int DEL_F = 26;
  public static final int FECHA = 18;
  public static final int MA_Q = 3;
  public static final int FS = 6;
  public static final int OPTION = 47;
  public static final int FECHA_MOD = 34;
  public static final int CREDEN_USER = 20;
  public static final int PASS = 17;
  public static final int IND = 43;
  public static final int CLASS = 42;
  public static final int SSS = 7;
  public static final int ID = 35;
  public static final int ADM = 4;
  public static final int L_C = 14;
  public static final int EOF = 0;
  public static final int L_A = 13;
  public static final int LOG_U = 24;
  public static final int C_C = 12;
  public static final int error = 1;
  public static final int C_A = 11;
  public static final int USER_NEW = 32;
  public static final int MO_U = 22;
  public static final int URL = 50;
  public static final int NAME = 37;
  public static final int ASIGNACION = 19;
  public static final int COM = 9;
  public static final int THEME = 38;
  public static final int TITLE = 36;
  public static final int MO_F = 27;
  public static final int COLM = 49;
  public static final int MO_C = 30;
  public static final int ME_Q = 2;
  public static final int USER_CRE = 39;
  public static final int EL_C = 29;
  public static final int D_DOT = 10;
  public static final int PARAMS_COMP = 21;
  public static final int ALI = 45;
  public static final int USER = 16;
  public static final int FILAS = 48;
  public static final int FSS = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ME_Q",
  "MA_Q",
  "ADM",
  "SS",
  "FS",
  "SSS",
  "FSS",
  "COM",
  "D_DOT",
  "C_A",
  "C_C",
  "L_A",
  "L_C",
  "CR_U",
  "USER",
  "PASS",
  "FECHA",
  "ASIGNACION",
  "CREDEN_USER",
  "PARAMS_COMP",
  "MO_U",
  "DEL_U",
  "LOG_U",
  "NEW_F",
  "DEL_F",
  "MO_F",
  "AGRE_C",
  "EL_C",
  "MO_C",
  "USER_ANT",
  "USER_NEW",
  "PASS_NEW",
  "FECHA_MOD",
  "ID",
  "TITLE",
  "NAME",
  "THEME",
  "USER_CRE",
  "NAME_CAMP",
  "FORM",
  "CLASS",
  "IND",
  "TEXT_VIEW",
  "ALI",
  "REQUE",
  "OPTION",
  "FILAS",
  "COLM",
  "URL"
  };
}

